# analytics
googleAnalytics = "UA-129126578-2"

baseURL = "/weblogic-kubernetes-operator/"
languageCode = "en-us"
title = "WebLogic Kubernetes Operator"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

publishDir = "docs"

canonifyURLs = true

# For search functionality
[outputs]
  home = [ "HTML", "RSS", "JSON"]

[params]
  # disable the copy to clipboard links
  disableInlineCopyToClipBoard = true

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 3
