apiVersion: v1
kind: Service
metadata:
  name: soadb
  labels:
    app: soadb
  namespace: soans
spec:
  ports:
  - port: 1521
    name: server-port
  - port: 5500
    name: em-port
  clusterIP: None
  selector:
    app: soadb
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: soadb
  namespace: soans
spec:
  serviceName: "soadb"
  replicas: 1
  template:
    metadata:
      labels:
        app: soadb
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: soadb
        image: oracle/database:12.2.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1521
          name: server-port
        - containerPort: 5500
          name: em-port
        env:
        - name: DB_SID
          value: soadb
        - name: DB_PDB
          value: soapdb
        - name: DB_DOMAIN
          value: my.domain.com
        - name: DB_BUNDLE
          value: basic
        readinessProbe:
          exec:
            command:
            - grep
            - "Done ! The database is ready for use ."
            - "/home/oracle/setup/log/setupDB.log"
          initialDelaySeconds: 300
          periodSeconds: 5
        volumeMounts:
        - mountPath: /ORCL
          name: soadb-storage
      volumes:
      - name: soadb-storage
        persistentVolumeClaim:
          claimName: soadb-pvc
