baseURL = "/weblogic-kubernetes-operator/"
languageCode = "en-us"
title = "WebLogic Kubernetes Operator"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

publishDir = "docs"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

