/* Copyright (c) 2017, 2018, Oracle and/or its affiliates. All rights reserved. */
/*
 * WebLogicDomain
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package oracle.kubernetes.operator.domain.model.oracle.kubernetes.weblogic.domain.v1;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ClusterStarup describes the desired startup state and passed environment
 * variables for a specific cluster.
 */
@ApiModel(description = "ClusterStarup describes the desired startup state and passed environment variables for a specific cluster.")

public class ClusterStartup {
  @SerializedName("desiredState")
  private String desiredState = null;

  @SerializedName("clusterName")
  private String clusterName = null;

  @SerializedName("replicas")
  private Integer replicas = null;

  @SerializedName("env")
  private List<io.kubernetes.client.models.V1EnvVar> env = null;

  public ClusterStartup desiredState(String desiredState) {
    this.desiredState = desiredState;
    return this;
  }

  /**
   * Desired startup state for any managed server started in this cluster. Legal
   * values are RUNNING or ADMIN.
   * 
   * @return desiredState
   **/
  @ApiModelProperty(value = "Desired startup state for any managed server started in this cluster. Legal values are RUNNING or ADMIN.")
  public String getDesiredState() {
    return desiredState;
  }

  public void setDesiredState(String desiredState) {
    this.desiredState = desiredState;
  }

  public ClusterStartup clusterName(String clusterName) {
    this.clusterName = clusterName;
    return this;
  }

  /**
   * Name of specific cluster to start. Managed servers in the cluster will be
   * started beginning with replicas instances.
   * 
   * @return clusterName
   **/
  @ApiModelProperty(required = true, value = "Name of specific cluster to start.  Managed servers in the cluster will be started beginning with replicas instances.")
  public String getClusterName() {
    return clusterName;
  }

  public void setClusterName(String clusterName) {
    this.clusterName = clusterName;
  }

  public ClusterStartup replicas(Integer replicas) {
    this.replicas = replicas;
    return this;
  }

  /**
   * Replicas is the desired number of managed servers running for this cluster.
   * 
   * @return replicas
   **/
  @ApiModelProperty(value = "Replicas is the desired number of managed servers running for this cluster.")
  public Integer getReplicas() {
    return replicas;
  }

  public void setReplicas(Integer replicas) {
    this.replicas = replicas;
  }

  public ClusterStartup env(List<io.kubernetes.client.models.V1EnvVar> env) {
    this.env = env;
    return this;
  }

  public ClusterStartup addEnvItem(io.kubernetes.client.models.V1EnvVar envItem) {
    if (this.env == null) {
      this.env = new ArrayList<io.kubernetes.client.models.V1EnvVar>();
    }
    this.env.add(envItem);
    return this;
  }

  /**
   * Environment variables to pass while starting managed servers in this cluster.
   * 
   * @return env
   **/
  @ApiModelProperty(value = "Environment variables to pass while starting managed servers in this cluster.")
  public List<io.kubernetes.client.models.V1EnvVar> getEnv() {
    return env;
  }

  public void setEnv(List<io.kubernetes.client.models.V1EnvVar> env) {
    this.env = env;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClusterStartup oracleKubernetesWeblogicDomainV1ClusterStartup = (ClusterStartup) o;
    return Objects.equals(this.desiredState, oracleKubernetesWeblogicDomainV1ClusterStartup.desiredState)
        && Objects.equals(this.clusterName, oracleKubernetesWeblogicDomainV1ClusterStartup.clusterName)
        && Objects.equals(this.replicas, oracleKubernetesWeblogicDomainV1ClusterStartup.replicas)
        && Objects.equals(this.env, oracleKubernetesWeblogicDomainV1ClusterStartup.env);
  }

  @Override
  public int hashCode() {
    return Objects.hash(desiredState, clusterName, replicas, env);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClusterStartup {\n");

    sb.append("    desiredState: ").append(toIndentedString(desiredState)).append("\n");
    sb.append("    clusterName: ").append(toIndentedString(clusterName)).append("\n");
    sb.append("    replicas: ").append(toIndentedString(replicas)).append("\n");
    sb.append("    env: ").append(toIndentedString(env)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
