/* Copyright (c) 2017, Oracle and/or its affiliates. All rights reserved. */
/*
 * WebLogicDomain
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package oracle.kubernetes.operator.domain.model.oracle.kubernetes.weblogic.domain.v1;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Domain represents a WebLogic domain and how it will be realized in the
 * Kubernetes cluster.
 */
@ApiModel(description = "Domain represents a WebLogic domain and how it will be realized in the Kubernetes cluster.")

public class Domain {
  @SerializedName("apiVersion")
  private String apiVersion = null;

  @SerializedName("kind")
  private String kind = null;

  @SerializedName("metadata")
  private io.kubernetes.client.models.V1ObjectMeta metadata = null;

  @SerializedName("spec")
  private DomainSpec spec = null;

  @SerializedName("status")
  private DomainStatus status = null;

  public Domain apiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

  /**
   * APIVersion defines the versioned schema of this representation of an object.
   * Servers should convert recognized schemas to the latest internal value, and
   * may reject unrecognized values. More info:
   * https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
   * 
   * @return apiVersion
   **/
  @ApiModelProperty(value = "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public Domain kind(String kind) {
    this.kind = kind;
    return this;
  }

  /**
   * Kind is a string value representing the REST resource this object represents.
   * Servers may infer this from the endpoint the client submits requests to.
   * Cannot be updated. In CamelCase. More info:
   * https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
   * 
   * @return kind
   **/
  @ApiModelProperty(value = "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public Domain metadata(io.kubernetes.client.models.V1ObjectMeta metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Standard object&#39;s metadata. More info:
   * https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
   * 
   * @return metadata
   **/
  @ApiModelProperty(value = "Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata")
  public io.kubernetes.client.models.V1ObjectMeta getMetadata() {
    return metadata;
  }

  public void setMetadata(io.kubernetes.client.models.V1ObjectMeta metadata) {
    this.metadata = metadata;
  }

  public Domain spec(DomainSpec spec) {
    this.spec = spec;
    return this;
  }

  /**
   * Specification of the desired behavior of the domain. More info:
   * https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status
   * 
   * @return spec
   **/
  @ApiModelProperty(value = "Specification of the desired behavior of the domain. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status")
  public DomainSpec getSpec() {
    return spec;
  }

  public void setSpec(DomainSpec spec) {
    this.spec = spec;
  }

  public Domain status(DomainStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Most recently observed status of the domain. This data may not be up to date.
   * Populated by the operator. Read-only. More info:
   * https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status
   * 
   * @return status
   **/
  @ApiModelProperty(value = "Most recently observed status of the domain. This data may not be up to date. Populated by the operator. Read-only. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status")
  public DomainStatus getStatus() {
    return status;
  }

  public void setStatus(DomainStatus status) {
    this.status = status;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Domain oracleKubernetesWeblogicDomainV1Domain = (Domain) o;
    return Objects.equals(this.apiVersion, oracleKubernetesWeblogicDomainV1Domain.apiVersion)
        && Objects.equals(this.kind, oracleKubernetesWeblogicDomainV1Domain.kind)
        && Objects.equals(this.metadata, oracleKubernetesWeblogicDomainV1Domain.metadata)
        && Objects.equals(this.spec, oracleKubernetesWeblogicDomainV1Domain.spec)
        && Objects.equals(this.status, oracleKubernetesWeblogicDomainV1Domain.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiVersion, kind, metadata, spec, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Domain {\n");

    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    spec: ").append(toIndentedString(spec)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
