# Copyright (c) 2025, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: Secret
metadata:
  name: weblogic-webhook-secrets
  namespace: placeholder
  labels:
    weblogic.webhookName: weblogic-operator
type: Opaque

