# Copyright (c) 2018, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

# Default values for ingress-per-domain.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Load balancer type.  Supported values are: TRAEFIK, NGINX
type: TRAEFIK

# WLS domain as backend to the load balancer
wlsDomain:
  domainUID: domain1
  clusterName: cluster-1
  managedServerPort: 8001

# Traefik specific values
traefik:
  # hostname used by host-routing
  hostname: domain1.org


# NGINX specific values
nginx:
  # hostname used by host-routing
  hostname: domain1.org
