kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: soadb-pvc
  namespace: soans
spec:
  storageClassName: db-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi