apiVersion: batch/v1
kind: Job
metadata:
  name: weblogic-command-job
  namespace: default
spec:
  template:
    metadata:
    spec:
      restartPolicy: Never
      activeDeadlineSeconds: 60
      containers:
        - name: domain-job
          image: store/oracle/weblogic:12.2.1.3
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /scratch
            name: scratch
          - mountPath: /scripts
            name: weblogic-command-job-configmap-volume
          command: ["/bin/bash"]
          args: ["-c", "COMMAND"]
      imagePullSecrets:
        - name: docker-store
      volumes:
        - name: scratch
          hostPath:
            path: PV_ROOT
        - name: weblogic-command-job-configmap-volume
          configMap:
            name: weblogic-command-job-configmap
            defaultMode: 0777
