// Copyright (c) 2021, 2022, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

package oracle.kubernetes.operator.helpers;

/**
 * To present pods from rolling when a customer upgrades the operator, we must test against the YAML that would
 * be generated in old operator versions for the settings in the PodHelper test.
 *
 * The settings here are taken from 3.0.0 and 3.1.0.
 */
class ReferenceObjects {
  static final String MANAGED_PLAINPORT_POD_3_0 =
        "metadata:\n"
        + "  annotations:\n"
        + "    prometheus.io/path: /wls-exporter/metrics\n"
        + "    prometheus.io/port: '8001'\n"
        + "    prometheus.io/scrape: 'true'\n"
        + "    weblogic.sha256: '6e1c6a716a9e0078a56c2df86ffe1cd2f0f9bdbe271f169dc1d548d026aa52b7'\n"
        + "  labels:\n"
        + "    weblogic.domainName: domain1\n"
        + "    weblogic.serverName: ess_server1\n"
        + "    weblogic.domainRestartVersion: null\n"
        + "    weblogic.domainUID: uid1\n"
        + "    weblogic.createdByOperator: 'true'\n"
        + "    weblogic.clusterRestartVersion: null\n"
        + "    weblogic.serverRestartVersion: null\n"
        + "  name: uid1-ess-server1\n"
        + "  namespace: namespace\n"
        + "  ownerReferences:\n"
        + "  - apiVersion: weblogic.oracle/v9\n"
        + "    kind: Domain\n"
        + "    controller: true\n"
        + "    name: domain1\n"
        + "    uid: '12345'\n"
        + "spec:\n"
        + "  containers:\n"
        + "  - command:\n"
        + "    - /weblogic-operator/scripts/startServer.sh\n"
        + "    env:\n"
        + "    - name: DOMAIN_NAME\n"
        + "      value: domain1\n"
        + "    - name: DOMAIN_HOME\n"
        + "      value: /u01/oracle/user_projects/domains\n"
        + "    - name: ADMIN_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: ADMIN_PORT\n"
        + "      value: '7001'\n"
        + "    - name: SERVER_NAME\n"
        + "      value: ess_server1\n"
        + "    - name: DOMAIN_UID\n"
        + "      value: uid1\n"
        + "    - name: NODEMGR_HOME\n"
        + "      value: /u01/nodemanager\n"
        + "    - name: LOG_HOME\n"
        + "    - name: SERVER_OUT_IN_POD_LOG\n"
        + "      value: 'true'\n"
        + "    - name: SERVICE_NAME\n"
        + "      value: uid1-ess-server1\n"
        + "    - name: AS_SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: USER_MEM_ARGS\n"
        + "      value: -Djava.security.egd=file:/dev/./urandom\n"
        + "    - name: ADMIN_USERNAME\n"
        + "    - name: ADMIN_PASSWORD\n"
        + "    - name: LOCAL_ADMIN_PORT\n"
        + "      value: '8001'\n"
        + "    - name: LOCAL_ADMIN_PROTOCOL\n"
        + "      value: t3\n"
        + "    - name: SHUTDOWN_TYPE\n"
        + "      value: Graceful\n"
        + "    - name: SHUTDOWN_TIMEOUT\n"
        + "      value: '30'\n"
        + "    - name: SHUTDOWN_IGNORE_SESSIONS\n"
        + "      value: 'false'\n"
        + "    - name: DYNAMIC_CONFIG_OVERRIDE\n"
        + "      value: 'true'\n"
        + "    image: image:latest\n"
        + "    imagePullPolicy: Always\n"
        + "    lifecycle:\n"
        + "      preStop:\n"
        + "        exec:\n"
        + "          command:\n"
        + "          - /weblogic-operator/scripts/stopServer.sh\n"
        + "    livenessProbe:\n"
        + "      exec:\n"
        + "        command:\n"
        + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
        + "      failureThreshold: 1\n"
        + "      initialDelaySeconds: 4\n"
        + "      periodSeconds: 6\n"
        + "      timeoutSeconds: 5\n"
        + "    name: weblogic-server\n"
        + "    ports:\n"
        + "    - containerPort: 8001\n"
        + "      name: default\n"
        + "      protocol: TCP\n"
        + "    readinessProbe:\n"
        + "      failureThreshold: 1\n"
        + "      httpGet:\n"
        + "        path: /weblogic/ready\n"
        + "        port: 8001\n"
        + "      initialDelaySeconds: 1\n"
        + "      periodSeconds: 3\n"
        + "      timeoutSeconds: 2\n"
        + "    resources:\n"
        + "      limits: {}\n"
        + "      requests: {}\n"
        + "    securityContext: {}\n"
        + "    volumeMounts:\n"
        + "    - mountPath: /weblogic-operator/scripts\n"
        + "      name: weblogic-scripts-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/debug\n"
        + "      name: weblogic-domain-debug-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/introspector\n"
        + "      name: weblogic-domain-introspect-cm-volume\n"
        + "  imagePullSecrets: []\n"
        + "  initContainers: []\n"
        + "  nodeSelector: {}\n"
        + "  securityContext: {}\n"
        + "  terminationGracePeriodSeconds: 40\n"
        + "  volumes:\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: weblogic-scripts-cm\n"
        + "    name: weblogic-scripts-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-debug-cm\n"
        + "      optional: true\n"
        + "    name: weblogic-domain-debug-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-introspect-cm\n"
        + "    name: weblogic-domain-introspect-cm-volume\n";

  static final String MANAGED_PLAINPORT_POD_3_1 =
        "metadata:\n"
        + "  annotations:\n"
        + "    prometheus.io/path: /wls-exporter/metrics\n"
        + "    prometheus.io/port: '8001'\n"
        + "    prometheus.io/scrape: 'true'\n"
        + "    weblogic.sha256: 6e1c6a716a9e0078a56c2df86ffe1cd2f0f9bdbe271f169dc1d548d026aa52b7\n"
        + "  labels:\n"
        + "    weblogic.domainName: domain1\n"
        + "    weblogic.serverName: ess_server1\n"
        + "    weblogic.domainRestartVersion: null\n"
        + "    weblogic.domainUID: uid1\n"
        + "    weblogic.createdByOperator: 'true'\n"
        + "    weblogic.clusterRestartVersion: null\n"
        + "    weblogic.serverRestartVersion: null\n"
        + "  name: uid1-ess-server1\n"
        + "  namespace: namespace\n"
        + "spec:\n"
        + "  containers:\n"
        + "  - command:\n"
        + "    - /weblogic-operator/scripts/startServer.sh\n"
        + "    env:\n"
        + "    - name: DOMAIN_NAME\n"
        + "      value: domain1\n"
        + "    - name: DOMAIN_HOME\n"
        + "      value: /u01/oracle/user_projects/domains\n"
        + "    - name: ADMIN_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: ADMIN_PORT\n"
        + "      value: '7001'\n"
        + "    - name: SERVER_NAME\n"
        + "      value: ess_server1\n"
        + "    - name: DOMAIN_UID\n"
        + "      value: uid1\n"
        + "    - name: NODEMGR_HOME\n"
        + "      value: /u01/nodemanager\n"
        + "    - name: LOG_HOME\n"
        + "    - name: SERVER_OUT_IN_POD_LOG\n"
        + "      value: 'true'\n"
        + "    - name: SERVICE_NAME\n"
        + "      value: uid1-ess-server1\n"
        + "    - name: AS_SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: USER_MEM_ARGS\n"
        + "      value: -Djava.security.egd=file:/dev/./urandom\n"
        + "    - name: ADMIN_USERNAME\n"
        + "    - name: ADMIN_PASSWORD\n"
        + "    image: image:latest\n"
        + "    imagePullPolicy: Always\n"
        + "    lifecycle:\n"
        + "      preStop:\n"
        + "        exec:\n"
        + "          command:\n"
        + "          - /weblogic-operator/scripts/stopServer.sh\n"
        + "    livenessProbe:\n"
        + "      exec:\n"
        + "        command:\n"
        + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
        + "      failureThreshold: 1\n"
        + "      initialDelaySeconds: 4\n"
        + "      periodSeconds: 6\n"
        + "      timeoutSeconds: 5\n"
        + "    name: weblogic-server\n"
        + "    ports:\n"
        + "    - containerPort: 8001\n"
        + "      name: default\n"
        + "      protocol: TCP\n"
        + "    readinessProbe:\n"
        + "      failureThreshold: 1\n"
        + "      httpGet:\n"
        + "        path: /weblogic/ready\n"
        + "        port: 8001\n"
        + "      initialDelaySeconds: 1\n"
        + "      periodSeconds: 3\n"
        + "      timeoutSeconds: 2\n"
        + "    resources:\n"
        + "      limits: {}\n"
        + "      requests: {}\n"
        + "    securityContext: {}\n"
        + "    volumeMounts:\n"
        + "    - mountPath: /weblogic-operator/scripts\n"
        + "      name: weblogic-scripts-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/debug\n"
        + "      name: weblogic-domain-debug-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/introspector\n"
        + "      name: weblogic-domain-introspect-cm-volume\n"
        + "  imagePullSecrets: []\n"
        + "  initContainers: []\n"
        + "  nodeSelector: {}\n"
        + "  securityContext: {}\n"
        + "  volumes:\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: weblogic-scripts-cm\n"
        + "    name: weblogic-scripts-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-debug-cm\n"
        + "      optional: true\n"
        + "    name: weblogic-domain-debug-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-introspect-cm\n"
        + "    name: weblogic-domain-introspect-cm-volume\n";

  static final String ADMIN_PLAINPORT_POD_3_0 =
        "metadata:\n"
        + "  annotations:\n"
        + "    prometheus.io/path: /wls-exporter/metrics\n"
        + "    prometheus.io/port: '7001'\n"
        + "    prometheus.io/scrape: 'true'\n"
        + "    weblogic.sha256: 'fc735cf7c34bc1492a237149c4e27c9bb27575de463dbc55e953588862098df4'\n"
        + "  labels:\n"
        + "    weblogic.domainName: domain1\n"
        + "    weblogic.serverName: ADMIN_SERVER\n"
        + "    weblogic.domainRestartVersion: null\n"
        + "    weblogic.domainUID: uid1\n"
        + "    weblogic.createdByOperator: 'true'\n"
        + "    weblogic.clusterRestartVersion: null\n"
        + "    weblogic.serverRestartVersion: null\n"
        + "  name: uid1-admin-server\n"
        + "  namespace: namespace\n"
        + "  ownerReferences:\n"
        + "  - apiVersion: weblogic.oracle/v9\n"
        + "    kind: Domain\n"
        + "    controller: true\n"
        + "    name: domain1\n"
        + "    uid: '12345'\n"
        + "spec:\n"
        + "  containers:\n"
        + "  - command:\n"
        + "    - /weblogic-operator/scripts/startServer.sh\n"
        + "    env:\n"
        + "    - name: DOMAIN_NAME\n"
        + "      value: domain1\n"
        + "    - name: DOMAIN_HOME\n"
        + "      value: /u01/oracle/user_projects/domains\n"
        + "    - name: ADMIN_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: ADMIN_PORT\n"
        + "      value: '7001'\n"
        + "    - name: SERVER_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: DOMAIN_UID\n"
        + "      value: uid1\n"
        + "    - name: NODEMGR_HOME\n"
        + "      value: /u01/nodemanager\n"
        + "    - name: LOG_HOME\n"
        + "    - name: SERVER_OUT_IN_POD_LOG\n"
        + "      value: 'true'\n"
        + "    - name: SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: AS_SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: USER_MEM_ARGS\n"
        + "      value: -Djava.security.egd=file:/dev/./urandom\n"
        + "    - name: ADMIN_USERNAME\n"
        + "    - name: ADMIN_PASSWORD\n"
        + "    - name: LOCAL_ADMIN_PORT\n"
        + "      value: '7001'\n"
        + "    - name: LOCAL_ADMIN_PROTOCOL\n"
        + "      value: t3\n"
        + "    - name: SHUTDOWN_TYPE\n"
        + "      value: Graceful\n"
        + "    - name: SHUTDOWN_TIMEOUT\n"
        + "      value: '30'\n"
        + "    - name: SHUTDOWN_IGNORE_SESSIONS\n"
        + "      value: 'false'\n"
        + "    - name: DYNAMIC_CONFIG_OVERRIDE\n"
        + "      value: 'true'\n"
        + "    - name: INTERNAL_OPERATOR_CERT\n"
        + "      value: encoded-cert-data\n"
        + "    image: image:latest\n"
        + "    imagePullPolicy: Always\n"
        + "    lifecycle:\n"
        + "      preStop:\n"
        + "        exec:\n"
        + "          command:\n"
        + "          - /weblogic-operator/scripts/stopServer.sh\n"
        + "    livenessProbe:\n"
        + "      exec:\n"
        + "        command:\n"
        + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
        + "      failureThreshold: 1\n"
        + "      initialDelaySeconds: 4\n"
        + "      periodSeconds: 6\n"
        + "      timeoutSeconds: 5\n"
        + "    name: weblogic-server\n"
        + "    ports:\n"
        + "    - containerPort: 7001\n"
        + "      name: default\n"
        + "      protocol: TCP\n"
        + "    readinessProbe:\n"
        + "      failureThreshold: 1\n"
        + "      httpGet:\n"
        + "        path: /weblogic/ready\n"
        + "        port: 7001\n"
        + "      initialDelaySeconds: 1\n"
        + "      periodSeconds: 3\n"
        + "      timeoutSeconds: 2\n"
        + "    resources:\n"
        + "      limits: {}\n"
        + "      requests: {}\n"
        + "    securityContext: {}\n"
        + "    volumeMounts:\n"
        + "    - mountPath: /weblogic-operator/scripts\n"
        + "      name: weblogic-scripts-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/debug\n"
        + "      name: weblogic-domain-debug-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/introspector\n"
        + "      name: weblogic-domain-introspect-cm-volume\n"
        + "  hostname: uid1-admin-server\n"
        + "  imagePullSecrets: []\n"
        + "  initContainers: []\n"
        + "  nodeSelector: {}\n"
        + "  securityContext: {}\n"
        + "  terminationGracePeriodSeconds: 40\n"
        + "  volumes:\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: weblogic-scripts-cm\n"
        + "    name: weblogic-scripts-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-debug-cm\n"
        + "      optional: true\n"
        + "    name: weblogic-domain-debug-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-introspect-cm\n"
        + "    name: weblogic-domain-introspect-cm-volume\n";


  static final String ADMIN_PLAINPORT_POD_3_1
        = "metadata:\n"
        + "  annotations:\n"
        + "    prometheus.io/path: /wls-exporter/metrics\n"
        + "    prometheus.io/port: '7001'\n"
        + "    prometheus.io/scrape: 'true'\n"
        + "    weblogic.sha256: fc735cf7c34bc1492a237149c4e27c9bb27575de463dbc55e953588862098df4\n"
        + "  labels:\n"
        + "    weblogic.domainName: domain1\n"
        + "    weblogic.serverName: ADMIN_SERVER\n"
        + "    weblogic.domainRestartVersion: null\n"
        + "    weblogic.domainUID: uid1\n"
        + "    weblogic.createdByOperator: 'true'\n"
        + "    weblogic.clusterRestartVersion: null\n"
        + "    weblogic.serverRestartVersion: null\n"
        + "  name: uid1-admin-server\n"
        + "  namespace: namespace\n"
        + "spec:\n"
        + "  containers:\n"
        + "  - command:\n"
        + "    - /weblogic-operator/scripts/startServer.sh\n"
        + "    env:\n"
        + "    - name: DOMAIN_NAME\n"
        + "      value: domain1\n"
        + "    - name: DOMAIN_HOME\n"
        + "      value: /u01/oracle/user_projects/domains\n"
        + "    - name: ADMIN_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: ADMIN_PORT\n"
        + "      value: '7001'\n"
        + "    - name: SERVER_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: DOMAIN_UID\n"
        + "      value: uid1\n"
        + "    - name: NODEMGR_HOME\n"
        + "      value: /u01/nodemanager\n"
        + "    - name: LOG_HOME\n"
        + "    - name: SERVER_OUT_IN_POD_LOG\n"
        + "      value: 'true'\n"
        + "    - name: SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: AS_SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: USER_MEM_ARGS\n"
        + "      value: -Djava.security.egd=file:/dev/./urandom\n"
        + "    - name: ADMIN_USERNAME\n"
        + "    - name: ADMIN_PASSWORD\n"
        + "    image: image:latest\n"
        + "    imagePullPolicy: Always\n"
        + "    lifecycle:\n"
        + "      preStop:\n"
        + "        exec:\n"
        + "          command:\n"
        + "          - /weblogic-operator/scripts/stopServer.sh\n"
        + "    livenessProbe:\n"
        + "      exec:\n"
        + "        command:\n"
        + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
        + "      failureThreshold: 1\n"
        + "      initialDelaySeconds: 4\n"
        + "      periodSeconds: 6\n"
        + "      timeoutSeconds: 5\n"
        + "    name: weblogic-server\n"
        + "    ports:\n"
        + "    - containerPort: 7001\n"
        + "      name: default\n"
        + "      protocol: TCP\n"
        + "    readinessProbe:\n"
        + "      failureThreshold: 1\n"
        + "      httpGet:\n"
        + "        path: /weblogic/ready\n"
        + "        port: 7001\n"
        + "      initialDelaySeconds: 1\n"
        + "      periodSeconds: 3\n"
        + "      timeoutSeconds: 2\n"
        + "    resources:\n"
        + "      limits: {}\n"
        + "      requests: {}\n"
        + "    securityContext: {}\n"
        + "    volumeMounts:\n"
        + "    - mountPath: /weblogic-operator/scripts\n"
        + "      name: weblogic-scripts-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/debug\n"
        + "      name: weblogic-domain-debug-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/introspector\n"
        + "      name: weblogic-domain-introspect-cm-volume\n"
        + "  hostname: uid1-admin-server\n"
        + "  imagePullSecrets: []\n"
        + "  initContainers: []\n"
        + "  nodeSelector: {}\n"
        + "  securityContext: {}\n"
        + "  volumes:\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: weblogic-scripts-cm\n"
        + "    name: weblogic-scripts-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-debug-cm\n"
        + "      optional: true\n"
        + "    name: weblogic-domain-debug-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-introspect-cm\n"
        + "    name: weblogic-domain-introspect-cm-volume\n";

  static final String MANAGED_SSLPORT_POD_3_0 =
        "metadata:\n"
        + "  annotations:\n"
        + "    prometheus.io/path: /wls-exporter/metrics\n"
        + "    prometheus.io/port: '8001'\n"
        + "    prometheus.io/scrape: 'true'\n"
        + "    weblogic.sha256: '368b26eaf1645f966d4c350906b59a0afcc0fbdf9ed30779b71a6d044eb480dd'\n"
        + "  labels:\n"
        + "    weblogic.domainName: domain1\n"
        + "    weblogic.serverName: ess_server1\n"
        + "    weblogic.domainRestartVersion: null\n"
        + "    weblogic.domainUID: uid1\n"
        + "    weblogic.createdByOperator: 'true'\n"
        + "    weblogic.clusterRestartVersion: null\n"
        + "    weblogic.serverRestartVersion: null\n"
        + "  name: uid1-ess-server1\n"
        + "  namespace: namespace\n"
        + "  ownerReferences:\n"
        + "  - apiVersion: weblogic.oracle/v9\n"
        + "    kind: Domain\n"
        + "    controller: true\n"
        + "    name: domain1\n"
        + "    uid: '12345'\n"
        + "spec:\n"
        + "  containers:\n"
        + "  - command:\n"
        + "    - /weblogic-operator/scripts/startServer.sh\n"
        + "    env:\n"
        + "    - name: DOMAIN_NAME\n"
        + "      value: domain1\n"
        + "    - name: DOMAIN_HOME\n"
        + "      value: /u01/oracle/user_projects/domains\n"
        + "    - name: ADMIN_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: ADMIN_PORT\n"
        + "      value: '7001'\n"
        + "    - name: ADMIN_PORT_SECURE\n"
        + "      value: 'true'\n"
        + "    - name: SERVER_NAME\n"
        + "      value: ess_server1\n"
        + "    - name: DOMAIN_UID\n"
        + "      value: uid1\n"
        + "    - name: NODEMGR_HOME\n"
        + "      value: /u01/nodemanager\n"
        + "    - name: LOG_HOME\n"
        + "    - name: SERVER_OUT_IN_POD_LOG\n"
        + "      value: 'true'\n"
        + "    - name: SERVICE_NAME\n"
        + "      value: uid1-ess-server1\n"
        + "    - name: AS_SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: USER_MEM_ARGS\n"
        + "      value: -Djava.security.egd=file:/dev/./urandom\n"
        + "    - name: ADMIN_USERNAME\n"
        + "    - name: ADMIN_PASSWORD\n"
        + "    - name: LOCAL_ADMIN_PORT\n"
        + "      value: '7002'\n"
        + "    - name: LOCAL_ADMIN_PROTOCOL\n"
        + "      value: t3s\n"
        + "    - name: SHUTDOWN_TYPE\n"
        + "      value: Graceful\n"
        + "    - name: SHUTDOWN_TIMEOUT\n"
        + "      value: '30'\n"
        + "    - name: SHUTDOWN_IGNORE_SESSIONS\n"
        + "      value: 'false'\n"
        + "    - name: DYNAMIC_CONFIG_OVERRIDE\n"
        + "      value: 'true'\n"
        + "    image: image:latest\n"
        + "    imagePullPolicy: Always\n"
        + "    lifecycle:\n"
        + "      preStop:\n"
        + "        exec:\n"
        + "          command:\n"
        + "          - /weblogic-operator/scripts/stopServer.sh\n"
        + "    livenessProbe:\n"
        + "      exec:\n"
        + "        command:\n"
        + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
        + "      failureThreshold: 1\n"
        + "      initialDelaySeconds: 4\n"
        + "      periodSeconds: 6\n"
        + "      timeoutSeconds: 5\n"
        + "    name: weblogic-server\n"
        + "    ports:\n"
        + "    - containerPort: 8001\n"
        + "      name: default\n"
        + "      protocol: TCP\n"
        + "    - containerPort: 7002\n"
        + "      name: default-secure\n"
        + "      protocol: TCP\n"
        + "    readinessProbe:\n"
        + "      failureThreshold: 1\n"
        + "      httpGet:\n"
        + "        path: /weblogic/ready\n"
        + "        port: 7002\n"
        + "        scheme: HTTPS\n"
        + "      initialDelaySeconds: 1\n"
        + "      periodSeconds: 3\n"
        + "      timeoutSeconds: 2\n"
        + "    resources:\n"
        + "      limits: {}\n"
        + "      requests: {}\n"
        + "    securityContext: {}\n"
        + "    volumeMounts:\n"
        + "    - mountPath: /weblogic-operator/scripts\n"
        + "      name: weblogic-scripts-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/debug\n"
        + "      name: weblogic-domain-debug-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/introspector\n"
        + "      name: weblogic-domain-introspect-cm-volume\n"
        + "  imagePullSecrets: []\n"
        + "  initContainers: []\n"
        + "  nodeSelector: {}\n"
        + "  securityContext: {}\n"
        + "  terminationGracePeriodSeconds: 40\n"
        + "  volumes:\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: weblogic-scripts-cm\n"
        + "    name: weblogic-scripts-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-debug-cm\n"
        + "      optional: true\n"
        + "    name: weblogic-domain-debug-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-introspect-cm\n"
        + "    name: weblogic-domain-introspect-cm-volume\n";
  
  static final String MANAGED_SSLPORT_POD_3_1 =
        "metadata:\n"
        + "  annotations:\n"
        + "    prometheus.io/path: /wls-exporter/metrics\n"
        + "    prometheus.io/port: '7002'\n"
        + "    prometheus.io/scrape: 'true'\n"
        + "    weblogic.sha256: 368b26eaf1645f966d4c350906b59a0afcc0fbdf9ed30779b71a6d044eb480dd\n"
        + "  labels:\n"
        + "    weblogic.domainName: domain1\n"
        + "    weblogic.serverName: ess_server1\n"
        + "    weblogic.domainRestartVersion: null\n"
        + "    weblogic.domainUID: uid1\n"
        + "    weblogic.createdByOperator: 'true'\n"
        + "    weblogic.clusterRestartVersion: null\n"
        + "    weblogic.serverRestartVersion: null\n"
        + "  name: uid1-ess-server1\n"
        + "  namespace: namespace\n"
        + "spec:\n"
        + "  containers:\n"
        + "  - command:\n"
        + "    - /weblogic-operator/scripts/startServer.sh\n"
        + "    env:\n"
        + "    - name: DOMAIN_NAME\n"
        + "      value: domain1\n"
        + "    - name: DOMAIN_HOME\n"
        + "      value: /u01/oracle/user_projects/domains\n"
        + "    - name: ADMIN_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: ADMIN_PORT\n"
        + "      value: '7001'\n"
        + "    - name: ADMIN_PORT_SECURE\n"
        + "      value: 'true'\n"
        + "    - name: SERVER_NAME\n"
        + "      value: ess_server1\n"
        + "    - name: DOMAIN_UID\n"
        + "      value: uid1\n"
        + "    - name: NODEMGR_HOME\n"
        + "      value: /u01/nodemanager\n"
        + "    - name: LOG_HOME\n"
        + "    - name: SERVER_OUT_IN_POD_LOG\n"
        + "      value: 'true'\n"
        + "    - name: SERVICE_NAME\n"
        + "      value: uid1-ess-server1\n"
        + "    - name: AS_SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: USER_MEM_ARGS\n"
        + "      value: -Djava.security.egd=file:/dev/./urandom\n"
        + "    - name: ADMIN_USERNAME\n"
        + "    - name: ADMIN_PASSWORD\n"
        + "    image: image:latest\n"
        + "    imagePullPolicy: Always\n"
        + "    lifecycle:\n"
        + "      preStop:\n"
        + "        exec:\n"
        + "          command:\n"
        + "          - /weblogic-operator/scripts/stopServer.sh\n"
        + "    livenessProbe:\n"
        + "      exec:\n"
        + "        command:\n"
        + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
        + "      failureThreshold: 1\n"
        + "      initialDelaySeconds: 4\n"
        + "      periodSeconds: 6\n"
        + "      timeoutSeconds: 5\n"
        + "    name: weblogic-server\n"
        + "    ports:\n"
        + "    - containerPort: 8001\n"
        + "      name: default\n"
        + "      protocol: TCP\n"
        + "    - containerPort: 7002\n"
        + "      name: default-secure\n"
        + "      protocol: TCP\n"
        + "    readinessProbe:\n"
        + "      failureThreshold: 1\n"
        + "      httpGet:\n"
        + "        path: /weblogic/ready\n"
        + "        port: 7002\n"
        + "        scheme: HTTPS\n"
        + "      initialDelaySeconds: 1\n"
        + "      periodSeconds: 3\n"
        + "      timeoutSeconds: 2\n"
        + "    resources:\n"
        + "      limits: {}\n"
        + "      requests: {}\n"
        + "    securityContext: {}\n"
        + "    volumeMounts:\n"
        + "    - mountPath: /weblogic-operator/scripts\n"
        + "      name: weblogic-scripts-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/debug\n"
        + "      name: weblogic-domain-debug-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/introspector\n"
        + "      name: weblogic-domain-introspect-cm-volume\n"
        + "  imagePullSecrets: []\n"
        + "  initContainers: []\n"
        + "  nodeSelector: {}\n"
        + "  securityContext: {}\n"
        + "  volumes:\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: weblogic-scripts-cm\n"
        + "    name: weblogic-scripts-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-debug-cm\n"
        + "      optional: true\n"
        + "    name: weblogic-domain-debug-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-introspect-cm\n"
        + "    name: weblogic-domain-introspect-cm-volume\n";

  static final String ADMIN_SSLPORT_POD_3_0 =
        "metadata:\n"
        + "  annotations:\n"
        + "    prometheus.io/path: /wls-exporter/metrics\n"
        + "    prometheus.io/port: '7002'\n"
        + "    prometheus.io/scrape: 'true'\n"
        + "    weblogic.sha256: '25dad014916d4e459419f1a38c67f3f3e44d4f2256f0e9edeb89a6c86ca22428'\n"
        + "  labels:\n"
        + "    weblogic.domainName: domain1\n"
        + "    weblogic.serverName: ADMIN_SERVER\n"
        + "    weblogic.domainRestartVersion: null\n"
        + "    weblogic.domainUID: uid1\n"
        + "    weblogic.createdByOperator: 'true'\n"
        + "    weblogic.clusterRestartVersion: null\n"
        + "    weblogic.serverRestartVersion: null\n"
        + "  name: uid1-admin-server\n"
        + "  namespace: namespace\n"
        + "  ownerReferences:\n"
        + "  - apiVersion: weblogic.oracle/v9\n"
        + "    kind: Domain\n"
        + "    controller: true\n"
        + "    name: domain1\n"
        + "    uid: '12345'\n"
        + "spec:\n"
        + "  containers:\n"
        + "  - command:\n"
        + "    - /weblogic-operator/scripts/startServer.sh\n"
        + "    env:\n"
        + "    - name: DOMAIN_NAME\n"
        + "      value: domain1\n"
        + "    - name: DOMAIN_HOME\n"
        + "      value: /u01/oracle/user_projects/domains\n"
        + "    - name: ADMIN_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: ADMIN_PORT\n"
        + "      value: '7002'\n"
        + "    - name: ADMIN_PORT_SECURE\n"
        + "      value: 'true'\n"
        + "    - name: ADMIN_SERVER_PORT_SECURE\n"
        + "      value: 'true'\n"
        + "    - name: SERVER_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: DOMAIN_UID\n"
        + "      value: uid1\n"
        + "    - name: NODEMGR_HOME\n"
        + "      value: /u01/nodemanager\n"
        + "    - name: LOG_HOME\n"
        + "    - name: SERVER_OUT_IN_POD_LOG\n"
        + "      value: 'true'\n"
        + "    - name: SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: AS_SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: USER_MEM_ARGS\n"
        + "      value: -Djava.security.egd=file:/dev/./urandom\n"
        + "    - name: ADMIN_USERNAME\n"
        + "    - name: ADMIN_PASSWORD\n"
        + "    - name: LOCAL_ADMIN_PORT\n"
        + "      value: '7002'\n"
        + "    - name: LOCAL_ADMIN_PROTOCOL\n"
        + "      value: t3s\n"
        + "    - name: SHUTDOWN_TYPE\n"
        + "      value: Graceful\n"
        + "    - name: SHUTDOWN_TIMEOUT\n"
        + "      value: '30'\n"
        + "    - name: SHUTDOWN_IGNORE_SESSIONS\n"
        + "      value: 'false'\n"
        + "    - name: DYNAMIC_CONFIG_OVERRIDE\n"
        + "      value: 'true'\n"
        + "    - name: INTERNAL_OPERATOR_CERT\n"
        + "      value: encoded-cert-data\n"
        + "    image: image:latest\n"
        + "    imagePullPolicy: Always\n"
        + "    lifecycle:\n"
        + "      preStop:\n"
        + "        exec:\n"
        + "          command:\n"
        + "          - /weblogic-operator/scripts/stopServer.sh\n"
        + "    livenessProbe:\n"
        + "      exec:\n"
        + "        command:\n"
        + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
        + "      failureThreshold: 1\n"
        + "      initialDelaySeconds: 4\n"
        + "      periodSeconds: 6\n"
        + "      timeoutSeconds: 5\n"
        + "    name: weblogic-server\n"
        + "    ports:\n"
        + "    - containerPort: 7001\n"
        + "      name: default\n"
        + "      protocol: TCP\n"
        + "    - containerPort: 7002\n"
        + "      name: default-secure\n"
        + "      protocol: TCP\n"
        + "    readinessProbe:\n"
        + "      failureThreshold: 1\n"
        + "      httpGet:\n"
        + "        path: /weblogic/ready\n"
        + "        port: 7002\n"
        + "        scheme: HTTPS\n"
        + "      initialDelaySeconds: 1\n"
        + "      periodSeconds: 3\n"
        + "      timeoutSeconds: 2\n"
        + "    resources:\n"
        + "      limits: {}\n"
        + "      requests: {}\n"
        + "    securityContext: {}\n"
        + "    volumeMounts:\n"
        + "    - mountPath: /weblogic-operator/scripts\n"
        + "      name: weblogic-scripts-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/debug\n"
        + "      name: weblogic-domain-debug-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/introspector\n"
        + "      name: weblogic-domain-introspect-cm-volume\n"
        + "  hostname: uid1-admin-server\n"
        + "  imagePullSecrets: []\n"
        + "  initContainers: []\n"
        + "  nodeSelector: {}\n"
        + "  securityContext: {}\n"
        + "  terminationGracePeriodSeconds: 40\n"
        + "  volumes:\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: weblogic-scripts-cm\n"
        + "    name: weblogic-scripts-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-debug-cm\n"
        + "      optional: true\n"
        + "    name: weblogic-domain-debug-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-introspect-cm\n"
        + "    name: weblogic-domain-introspect-cm-volume\n";

  static final String ADMIN_SSLPORT_POD_3_1 =
        "metadata:\n"
        + "  annotations:\n"
        + "    prometheus.io/path: /wls-exporter/metrics\n"
        + "    prometheus.io/port: '7002'\n"
        + "    prometheus.io/scrape: 'true'\n"
        + "    weblogic.sha256: 854c2ce0b646268a7e72f601f625a8466f45d71f7f635a65ad3740ecb9bdf39a\n"
        + "  labels:\n"
        + "    weblogic.domainName: domain1\n"
        + "    weblogic.serverName: ADMIN_SERVER\n"
        + "    weblogic.domainRestartVersion: null\n"
        + "    weblogic.domainUID: uid1\n"
        + "    weblogic.createdByOperator: 'true'\n"
        + "    weblogic.clusterRestartVersion: null\n"
        + "    weblogic.serverRestartVersion: null\n"
        + "  name: uid1-admin-server\n"
        + "  namespace: namespace\n"
        + "spec:\n"
        + "  containers:\n"
        + "  - command:\n"
        + "    - /weblogic-operator/scripts/startServer.sh\n"
        + "    env:\n"
        + "    - name: DOMAIN_NAME\n"
        + "      value: domain1\n"
        + "    - name: DOMAIN_HOME\n"
        + "      value: /u01/oracle/user_projects/domains\n"
        + "    - name: ADMIN_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: ADMIN_PORT\n"
        + "      value: '7002'\n"
        + "    - name: ADMIN_PORT_SECURE\n"
        + "      value: 'true'\n"
        + "    - name: ADMIN_SERVER_PORT_SECURE\n"
        + "      value: 'true'\n"
        + "    - name: SERVER_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: DOMAIN_UID\n"
        + "      value: uid1\n"
        + "    - name: NODEMGR_HOME\n"
        + "      value: /u01/nodemanager\n"
        + "    - name: LOG_HOME\n"
        + "    - name: SERVER_OUT_IN_POD_LOG\n"
        + "      value: 'true'\n"
        + "    - name: SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: AS_SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: USER_MEM_ARGS\n"
        + "      value: -Djava.security.egd=file:/dev/./urandom\n"
        + "    - name: ADMIN_USERNAME\n"
        + "    - name: ADMIN_PASSWORD\n"
        + "    image: image:latest\n"
        + "    imagePullPolicy: Always\n"
        + "    lifecycle:\n"
        + "      preStop:\n"
        + "        exec:\n"
        + "          command:\n"
        + "          - /weblogic-operator/scripts/stopServer.sh\n"
        + "    livenessProbe:\n"
        + "      exec:\n"
        + "        command:\n"
        + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
        + "      failureThreshold: 1\n"
        + "      initialDelaySeconds: 4\n"
        + "      periodSeconds: 6\n"
        + "      timeoutSeconds: 5\n"
        + "    name: weblogic-server\n"
        + "    ports:\n"
        + "    - containerPort: 7001\n"
        + "      name: default\n"
        + "      protocol: TCP\n"
        + "    - containerPort: 7002\n"
        + "      name: default-secure\n"
        + "      protocol: TCP\n"
        + "    readinessProbe:\n"
        + "      failureThreshold: 1\n"
        + "      httpGet:\n"
        + "        path: /weblogic/ready\n"
        + "        port: 7002\n"
        + "        scheme: HTTPS\n"
        + "      initialDelaySeconds: 1\n"
        + "      periodSeconds: 3\n"
        + "      timeoutSeconds: 2\n"
        + "    resources:\n"
        + "      limits: {}\n"
        + "      requests: {}\n"
        + "    securityContext: {}\n"
        + "    volumeMounts:\n"
        + "    - mountPath: /weblogic-operator/scripts\n"
        + "      name: weblogic-scripts-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/debug\n"
        + "      name: weblogic-domain-debug-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/introspector\n"
        + "      name: weblogic-domain-introspect-cm-volume\n"
        + "  hostname: uid1-admin-server\n"
        + "  imagePullSecrets: []\n"
        + "  initContainers: []\n"
        + "  nodeSelector: {}\n"
        + "  securityContext: {}\n"
        + "  volumes:\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: weblogic-scripts-cm\n"
        + "    name: weblogic-scripts-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-debug-cm\n"
        + "      optional: true\n"
        + "    name: weblogic-domain-debug-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-introspect-cm\n"
        + "    name: weblogic-domain-introspect-cm-volume\n";

  static final String MANAGED_MII_POD_3_1 =
        "metadata:\n"
        + "  annotations:\n"
        + "    prometheus.io/path: /wls-exporter/metrics\n"
        + "    prometheus.io/port: '8001'\n"
        + "    prometheus.io/scrape: 'true'\n"
        + "    weblogic.sha256: bdebf4e8152fea393e06f037bbb4ed243a938f2f9e1aeeffe20768724a0b32cc\n"
        + "  labels:\n"
        + "    weblogic.domainName: domain1\n"
        + "    weblogic.serverName: ess_server1\n"
        + "    weblogic.modelInImageModelSecretsHash: md5.originalSecret.md5\n"
        + "    weblogic.domainRestartVersion: null\n"
        + "    weblogic.domainUID: uid1\n"
        + "    weblogic.createdByOperator: 'true'\n"
        + "    weblogic.modelInImageDomainZipHash: md5.originalSecret.md5\n"
        + "    weblogic.clusterRestartVersion: null\n"
        + "    weblogic.serverRestartVersion: null\n"
        + "  name: uid1-ess-server1\n"
        + "  namespace: namespace\n"
        + "spec:\n"
        + "  containers:\n"
        + "  - command:\n"
        + "    - /weblogic-operator/scripts/startServer.sh\n"
        + "    env:\n"
        + "    - name: DOMAIN_NAME\n"
        + "      value: domain1\n"
        + "    - name: DOMAIN_HOME\n"
        + "      value: /u01/oracle/user_projects/domains\n"
        + "    - name: ADMIN_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: ADMIN_PORT\n"
        + "      value: '7001'\n"
        + "    - name: SERVER_NAME\n"
        + "      value: ess_server1\n"
        + "    - name: DOMAIN_UID\n"
        + "      value: uid1\n"
        + "    - name: NODEMGR_HOME\n"
        + "      value: /u01/nodemanager\n"
        + "    - name: LOG_HOME\n"
        + "    - name: SERVER_OUT_IN_POD_LOG\n"
        + "      value: 'true'\n"
        + "    - name: SERVICE_NAME\n"
        + "      value: uid1-ess-server1\n"
        + "    - name: AS_SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: USER_MEM_ARGS\n"
        + "      value: -Djava.security.egd=file:/dev/./urandom\n"
        + "    - name: ADMIN_USERNAME\n"
        + "    - name: ADMIN_PASSWORD\n"
        + "    image: image:latest\n"
        + "    imagePullPolicy: Always\n"
        + "    lifecycle:\n"
        + "      preStop:\n"
        + "        exec:\n"
        + "          command:\n"
        + "          - /weblogic-operator/scripts/stopServer.sh\n"
        + "    livenessProbe:\n"
        + "      exec:\n"
        + "        command:\n"
        + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
        + "      failureThreshold: 1\n"
        + "      initialDelaySeconds: 4\n"
        + "      periodSeconds: 6\n"
        + "      timeoutSeconds: 5\n"
        + "    name: weblogic-server\n"
        + "    ports:\n"
        + "    - containerPort: 8001\n"
        + "      name: default\n"
        + "      protocol: TCP\n"
        + "    readinessProbe:\n"
        + "      failureThreshold: 1\n"
        + "      httpGet:\n"
        + "        path: /weblogic/ready\n"
        + "        port: 8001\n"
        + "      initialDelaySeconds: 1\n"
        + "      periodSeconds: 3\n"
        + "      timeoutSeconds: 2\n"
        + "    resources:\n"
        + "      limits: {}\n"
        + "      requests: {}\n"
        + "    securityContext: {}\n"
        + "    volumeMounts:\n"
        + "    - mountPath: /weblogic-operator/scripts\n"
        + "      name: weblogic-scripts-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/debug\n"
        + "      name: weblogic-domain-debug-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/introspector\n"
        + "      name: weblogic-domain-introspect-cm-volume\n"
        + "  imagePullSecrets: []\n"
        + "  initContainers: []\n"
        + "  nodeSelector: {}\n"
        + "  securityContext: {}\n"
        + "  volumes:\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: weblogic-scripts-cm\n"
        + "    name: weblogic-scripts-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-debug-cm\n"
        + "      optional: true\n"
        + "    name: weblogic-domain-debug-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-introspect-cm\n"
        + "    name: weblogic-domain-introspect-cm-volume";

  static final String ADMIN_MII_POD_3_1 =
        "metadata:\n"
        + "  annotations:\n"
        + "    prometheus.io/path: /wls-exporter/metrics\n"
        + "    prometheus.io/port: '7001'\n"
        + "    prometheus.io/scrape: 'true'\n"
        + "    weblogic.sha256: 98ac04bc5ddbc792ee37912ea5efe8097016ed10ce93b13f8e57013547429e6c\n"
        + "  labels:\n"
        + "    weblogic.domainName: domain1\n"
        + "    weblogic.serverName: ADMIN_SERVER\n"
        + "    weblogic.modelInImageModelSecretsHash: md5.originalSecret.md5\n"
        + "    weblogic.domainRestartVersion: null\n"
        + "    weblogic.domainUID: uid1\n"
        + "    weblogic.createdByOperator: 'true'\n"
        + "    weblogic.modelInImageDomainZipHash: md5.originalSecret.md5\n"
        + "    weblogic.clusterRestartVersion: null\n"
        + "    weblogic.serverRestartVersion: null\n"
        + "  name: uid1-admin-server\n"
        + "  namespace: namespace\n"
        + "spec:\n"
        + "  containers:\n"
        + "  - command:\n"
        + "    - /weblogic-operator/scripts/startServer.sh\n"
        + "    env:\n"
        + "    - name: DOMAIN_NAME\n"
        + "      value: domain1\n"
        + "    - name: DOMAIN_HOME\n"
        + "      value: /u01/oracle/user_projects/domains\n"
        + "    - name: ADMIN_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: ADMIN_PORT\n"
        + "      value: '7001'\n"
        + "    - name: SERVER_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: DOMAIN_UID\n"
        + "      value: uid1\n"
        + "    - name: NODEMGR_HOME\n"
        + "      value: /u01/nodemanager\n"
        + "    - name: LOG_HOME\n"
        + "    - name: SERVER_OUT_IN_POD_LOG\n"
        + "      value: 'true'\n"
        + "    - name: SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: AS_SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: USER_MEM_ARGS\n"
        + "      value: -Djava.security.egd=file:/dev/./urandom\n"
        + "    - name: ADMIN_USERNAME\n"
        + "    - name: ADMIN_PASSWORD\n"
        + "    image: image:latest\n"
        + "    imagePullPolicy: Always\n"
        + "    lifecycle:\n"
        + "      preStop:\n"
        + "        exec:\n"
        + "          command:\n"
        + "          - /weblogic-operator/scripts/stopServer.sh\n"
        + "    livenessProbe:\n"
        + "      exec:\n"
        + "        command:\n"
        + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
        + "      failureThreshold: 1\n"
        + "      initialDelaySeconds: 4\n"
        + "      periodSeconds: 6\n"
        + "      timeoutSeconds: 5\n"
        + "    name: weblogic-server\n"
        + "    ports:\n"
        + "    - containerPort: 7001\n"
        + "      name: default\n"
        + "      protocol: TCP\n"
        + "    readinessProbe:\n"
        + "      failureThreshold: 1\n"
        + "      httpGet:\n"
        + "        path: /weblogic/ready\n"
        + "        port: 7001\n"
        + "      initialDelaySeconds: 1\n"
        + "      periodSeconds: 3\n"
        + "      timeoutSeconds: 2\n"
        + "    resources:\n"
        + "      limits: {}\n"
        + "      requests: {}\n"
        + "    securityContext: {}\n"
        + "    volumeMounts:\n"
        + "    - mountPath: /weblogic-operator/scripts\n"
        + "      name: weblogic-scripts-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/debug\n"
        + "      name: weblogic-domain-debug-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/introspector\n"
        + "      name: weblogic-domain-introspect-cm-volume\n"
        + "  hostname: uid1-admin-server\n"
        + "  imagePullSecrets: []\n"
        + "  initContainers: []\n"
        + "  nodeSelector: {}\n"
        + "  securityContext: {}\n"
        + "  volumes:\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: weblogic-scripts-cm\n"
        + "    name: weblogic-scripts-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-debug-cm\n"
        + "      optional: true\n"
        + "    name: weblogic-domain-debug-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-introspect-cm\n"
        + "    name: weblogic-domain-introspect-cm-volume";

  static final String ADMIN_MII_AUX_IMAGE_POD_3_3 =
      "metadata:\n"
          + "  annotations:\n"
          + "    prometheus.io/path: /wls-exporter/metrics\n"
          + "    prometheus.io/port: '7001'\n"
          + "    prometheus.io/scrape: 'true'\n"
          + "    weblogic.sha256: fac693bf796af7a92f7dfe6752369140aad5ba2f4f8926d32a14a624c79a37fc\n"
          + "  labels:\n"
          + "    weblogic.domainName: domain1\n"
          + "    weblogic.serverName: ADMIN_SERVER\n"
          + "    weblogic.domainRestartVersion: null\n"
          + "    weblogic.domainUID: uid1\n"
          + "    weblogic.createdByOperator: 'true'\n"
          + "    weblogic.operatorVersion: 3.3.8\n"
          + "    weblogic.clusterRestartVersion: null\n"
          + "    weblogic.serverRestartVersion: null\n"
          + "  name: uid1-admin-server\n"
          + "  namespace: namespace\n"
          + "spec:\n"
          + "  containers:\n"
          + "  - command:\n"
          + "    - /weblogic-operator/scripts/startServer.sh\n"
          + "    env:\n"
          + "    - name: DOMAIN_NAME\n"
          + "      value: domain1\n"
          + "    - name: DOMAIN_HOME\n"
          + "      value: /u01/oracle/user_projects/domains\n"
          + "    - name: ADMIN_NAME\n"
          + "      value: ADMIN_SERVER\n"
          + "    - name: ADMIN_PORT\n"
          + "      value: '7001'\n"
          + "    - name: SERVER_NAME\n"
          + "      value: ADMIN_SERVER\n"
          + "    - name: DOMAIN_UID\n"
          + "      value: uid1\n"
          + "    - name: NODEMGR_HOME\n"
          + "      value: /u01/nodemanager\n"
          + "    - name: LOG_HOME\n"
          + "    - name: SERVER_OUT_IN_POD_LOG\n"
          + "      value: 'true'\n"
          + "    - name: SERVICE_NAME\n"
          + "      value: uid1-admin-server\n"
          + "    - name: AS_SERVICE_NAME\n"
          + "      value: uid1-admin-server\n"
          + "    - name: USER_MEM_ARGS\n"
          + "      value: -Djava.security.egd=file:/dev/./urandom\n"
          + "    - name: ADMIN_USERNAME\n"
          + "    - name: ADMIN_PASSWORD\n"
          + "    image: image:latest\n"
          + "    imagePullPolicy: Always\n"
          + "    lifecycle:\n"
          + "      preStop:\n"
          + "        exec:\n"
          + "          command:\n"
          + "          - /weblogic-operator/scripts/stopServer.sh\n"
          + "    livenessProbe:\n"
          + "      exec:\n"
          + "        command:\n"
          + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
          + "      failureThreshold: 1\n"
          + "      initialDelaySeconds: 4\n"
          + "      periodSeconds: 6\n"
          + "      timeoutSeconds: 5\n"
          + "    name: weblogic-server\n"
          + "    ports:\n"
          + "    - containerPort: 7001\n"
          + "      name: default\n"
          + "      protocol: TCP\n"
          + "    readinessProbe:\n"
          + "      failureThreshold: 1\n"
          + "      httpGet:\n"
          + "        path: /weblogic/ready\n"
          + "        port: 7001\n"
          + "      initialDelaySeconds: 1\n"
          + "      periodSeconds: 3\n"
          + "      timeoutSeconds: 2\n"
          + "    resources:\n"
          + "      limits: {}\n"
          + "      requests:\n"
          + "        memory: 768Mi\n"
          + "        cpu: 250m\n"
          + "    securityContext: {}\n"
          + "    volumeMounts:\n"
          + "    - mountPath: /weblogic-operator/scripts\n"
          + "      name: weblogic-scripts-cm-volume\n"
          + "      readOnly: true\n"
          + "    - mountPath: /weblogic-operator/debug\n"
          + "      name: weblogic-domain-debug-cm-volume\n"
          + "      readOnly: true\n"
          + "    - mountPath: /weblogic-operator/introspector\n"
          + "      name: weblogic-domain-introspect-cm-volume\n"
          + "    - mountPath: /auxiliary\n"
          + "      name: aux-image-volume-auxiliaryimagevolume1\n"
          + "  hostname: uid1-admin-server\n"
          + "  imagePullSecrets: []\n"
          + "  initContainers:\n"
          + "  - command:\n"
          + "    - /weblogic-operator/scripts/auxImage.sh\n"
          + "    env:\n"
          + "    - name: AUXILIARY_IMAGE_PATH\n"
          + "      value: /auxiliary\n"
          + "    - name: AUXILIARY_IMAGE_TARGET_PATH\n"
          + "      value: /tmpAuxiliaryImage\n"
          + "    - name: AUXILIARY_IMAGE_COMMAND\n"
          + "      value: cp -R $AUXILIARY_IMAGE_PATH/* $AUXILIARY_IMAGE_TARGET_PATH\n"
          + "    - name: AUXILIARY_IMAGE_CONTAINER_IMAGE\n"
          + "      value: model-in-image:WLS-AI-v1\n"
          + "    - name: AUXILIARY_IMAGE_CONTAINER_NAME\n"
          + "      value: operator-aux-container1\n"
          + "    image: model-in-image:WLS-AI-v1\n"
          + "    imagePullPolicy: IfNotPresent\n"
          + "    name: operator-aux-container1\n"
          + "    volumeMounts:\n"
          + "    - mountPath: /tmpAuxiliaryImage\n"
          + "      name: aux-image-volume-auxiliaryimagevolume1\n"
          + "    - mountPath: /weblogic-operator/scripts\n"
          + "      name: weblogic-scripts-cm-volume\n"
          + "  nodeSelector: {}\n"
          + "  securityContext: {}\n"
          + "  volumes:\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: weblogic-scripts-cm\n"
          + "    name: weblogic-scripts-cm-volume\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: uid1-weblogic-domain-debug-cm\n"
          + "      optional: true\n"
          + "    name: weblogic-domain-debug-cm-volume\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: uid1-weblogic-domain-introspect-cm\n"
          + "    name: weblogic-domain-introspect-cm-volume\n"
          + "  - emptyDir: {}\n"
          + "    name: aux-image-volume-auxiliaryimagevolume1\n";

  static final String MANAGED_MII_AUX_IMAGE_POD_3_3 =
      "metadata:\n"
          + "  annotations:\n"
          + "    prometheus.io/path: /wls-exporter/metrics\n"
          + "    prometheus.io/port: '7001'\n"
          + "    prometheus.io/scrape: 'true'\n"
          + "    weblogic.sha256: 35a9ab3f5e0cd6878ae0bef19ec0dbddb099d9a24d829f4e83c36e42e93d5ab0\n"
          + "  labels:\n"
          + "    weblogic.domainName: domain1\n"
          + "    weblogic.serverName: ess_server1\n"
          + "    weblogic.domainRestartVersion: null\n"
          + "    weblogic.domainUID: uid1\n"
          + "    weblogic.createdByOperator: 'true'\n"
          + "    weblogic.operatorVersion: 3.3.8\n"
          + "    weblogic.clusterRestartVersion: null\n"
          + "    weblogic.serverRestartVersion: null\n"
          + "  name: uid1-ess-server1\n"
          + "  namespace: namespace\n"
          + "spec:\n"
          + "  containers:\n"
          + "  - command:\n"
          + "    - /weblogic-operator/scripts/startServer.sh\n"
          + "    env:\n"
          + "    - name: DOMAIN_NAME\n"
          + "      value: domain1\n"
          + "    - name: DOMAIN_HOME\n"
          + "      value: /u01/oracle/user_projects/domains\n"
          + "    - name: ADMIN_NAME\n"
          + "      value: ADMIN_SERVER\n"
          + "    - name: ADMIN_PORT\n"
          + "      value: '7001'\n"
          + "    - name: SERVER_NAME\n"
          + "      value: ess_server1\n"
          + "    - name: DOMAIN_UID\n"
          + "      value: uid1\n"
          + "    - name: NODEMGR_HOME\n"
          + "      value: /u01/nodemanager\n"
          + "    - name: LOG_HOME\n"
          + "    - name: SERVER_OUT_IN_POD_LOG\n"
          + "      value: 'true'\n"
          + "    - name: SERVICE_NAME\n"
          + "      value: uid1-ess-server1\n"
          + "    - name: AS_SERVICE_NAME\n"
          + "      value: uid1-admin-server\n"
          + "    - name: USER_MEM_ARGS\n"
          + "      value: -Djava.security.egd=file:/dev/./urandom\n"
          + "    - name: ADMIN_USERNAME\n"
          + "    - name: ADMIN_PASSWORD\n"
          + "    image: image:latest\n"
          + "    imagePullPolicy: Always\n"
          + "    lifecycle:\n"
          + "      preStop:\n"
          + "        exec:\n"
          + "          command:\n"
          + "          - /weblogic-operator/scripts/stopServer.sh\n"
          + "    livenessProbe:\n"
          + "      exec:\n"
          + "        command:\n"
          + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
          + "      failureThreshold: 1\n"
          + "      initialDelaySeconds: 4\n"
          + "      periodSeconds: 6\n"
          + "      timeoutSeconds: 5\n"
          + "    name: weblogic-server\n"
          + "    ports:\n"
          + "    - containerPort: 8001\n"
          + "      name: default\n"
          + "      protocol: TCP\n"
          + "    readinessProbe:\n"
          + "      failureThreshold: 1\n"
          + "      httpGet:\n"
          + "        path: /weblogic/ready\n"
          + "        port: 8001\n"
          + "      initialDelaySeconds: 1\n"
          + "      periodSeconds: 3\n"
          + "      timeoutSeconds: 2\n"
          + "    resources:\n"
          + "      limits: {}\n"
          + "      requests:\n"
          + "        memory: 768Mi\n"
          + "        cpu: 250m\n"
          + "    securityContext: {}\n"
          + "    volumeMounts:\n"
          + "    - mountPath: /weblogic-operator/scripts\n"
          + "      name: weblogic-scripts-cm-volume\n"
          + "      readOnly: true\n"
          + "    - mountPath: /weblogic-operator/debug\n"
          + "      name: weblogic-domain-debug-cm-volume\n"
          + "      readOnly: true\n"
          + "    - mountPath: /weblogic-operator/introspector\n"
          + "      name: weblogic-domain-introspect-cm-volume\n"
          + "    - mountPath: /auxiliary\n"
          + "      name: aux-image-volume-auxiliaryimagevolume1\n"
          + "  imagePullSecrets: []\n"
          + "  initContainers:\n"
          + "  - command:\n"
          + "    - /weblogic-operator/scripts/auxImage.sh\n"
          + "    env:\n"
          + "    - name: AUXILIARY_IMAGE_PATH\n"
          + "      value: /auxiliary\n"
          + "    - name: AUXILIARY_IMAGE_TARGET_PATH\n"
          + "      value: /tmpAuxiliaryImage\n"
          + "    - name: AUXILIARY_IMAGE_COMMAND\n"
          + "      value: cp -R $AUXILIARY_IMAGE_PATH/* $AUXILIARY_IMAGE_TARGET_PATH\n"
          + "    - name: AUXILIARY_IMAGE_CONTAINER_IMAGE\n"
          + "      value: model-in-image:WLS-AI-v1\n"
          + "    - name: AUXILIARY_IMAGE_CONTAINER_NAME\n"
          + "      value: operator-aux-container1\n"
          + "    image: model-in-image:WLS-AI-v1\n"
          + "    imagePullPolicy: IfNotPresent\n"
          + "    name: operator-aux-container1\n"
          + "    volumeMounts:\n"
          + "    - mountPath: /tmpAuxiliaryImage\n"
          + "      name: aux-image-volume-auxiliaryimagevolume1\n"
          + "    - mountPath: /weblogic-operator/scripts\n"
          + "      name: weblogic-scripts-cm-volume\n"
          + "  nodeSelector: {}\n"
          + "  securityContext: {}\n"
          + "  volumes:\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: weblogic-scripts-cm\n"
          + "    name: weblogic-scripts-cm-volume\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: uid1-weblogic-domain-debug-cm\n"
          + "      optional: true\n"
          + "    name: weblogic-domain-debug-cm-volume\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: uid1-weblogic-domain-introspect-cm\n"
          + "    name: weblogic-domain-introspect-cm-volume\n"
          + "  - emptyDir: {}\n"
          + "    name: aux-image-volume-auxiliaryimagevolume1\n";

  static final String ADMIN_MII_CONVERTED_AUX_IMAGE_POD_3_4 =
      "metadata:\n"
          + "  annotations:\n"
          + "    prometheus.io/path: /wls-exporter/metrics\n"
          + "    prometheus.io/port: '7001'\n"
          + "    prometheus.io/scrape: 'true'\n"
          + "    weblogic.sha256: 2b5624351965754377ba6f96fc3ff4ae43c4cd6f7045d435001038ae06b8db5a\n"
          + "  labels:\n"
          + "    weblogic.domainName: domain1\n"
          + "    weblogic.serverName: ADMIN_SERVER\n"
          + "    weblogic.domainRestartVersion: null\n"
          + "    weblogic.domainUID: uid1\n"
          + "    weblogic.createdByOperator: 'true'\n"
          + "    weblogic.operatorVersion: 3.4.0\n"
          + "    weblogic.clusterRestartVersion: null\n"
          + "    weblogic.serverRestartVersion: null\n"
          + "  name: uid1-admin-server\n"
          + "  namespace: namespace\n"
          + "spec:\n"
          + "  containers:\n"
          + "  - command:\n"
          + "    - /weblogic-operator/scripts/startServer.sh\n"
          + "    env:\n"
          + "    - name: DOMAIN_NAME\n"
          + "      value: domain1\n"
          + "    - name: DOMAIN_HOME\n"
          + "      value: /u01/oracle/user_projects/domains\n"
          + "    - name: ADMIN_NAME\n"
          + "      value: ADMIN_SERVER\n"
          + "    - name: ADMIN_PORT\n"
          + "      value: '7001'\n"
          + "    - name: SERVER_NAME\n"
          + "      value: ADMIN_SERVER\n"
          + "    - name: DOMAIN_UID\n"
          + "      value: uid1\n"
          + "    - name: NODEMGR_HOME\n"
          + "      value: /u01/nodemanager\n"
          + "    - name: LOG_HOME\n"
          + "    - name: SERVER_OUT_IN_POD_LOG\n"
          + "      value: 'true'\n"
          + "    - name: SERVICE_NAME\n"
          + "      value: uid1-admin-server\n"
          + "    - name: AS_SERVICE_NAME\n"
          + "      value: uid1-admin-server\n"
          + "    - name: USER_MEM_ARGS\n"
          + "      value: -Djava.security.egd=file:/dev/./urandom\n"
          + "    - name: WDT_INSTALL_HOME\n"
          + "      value: /auxiliary/weblogic-deploy\n"
          + "    - name: WDT_MODEL_HOME\n"
          + "      value: /auxiliary/models\n"
          + "    - name: AUXILIARY_IMAGE_PATHS\n"
          + "      value: /auxiliary\n"
          + "    - name: ADMIN_USERNAME\n"
          + "    - name: ADMIN_PASSWORD\n"
          + "    image: image:latest\n"
          + "    imagePullPolicy: Always\n"
          + "    lifecycle:\n"
          + "      preStop:\n"
          + "        exec:\n"
          + "          command:\n"
          + "          - /weblogic-operator/scripts/stopServer.sh\n"
          + "    livenessProbe:\n"
          + "      exec:\n"
          + "        command:\n"
          + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
          + "      failureThreshold: 1\n"
          + "      initialDelaySeconds: 4\n"
          + "      periodSeconds: 6\n"
          + "      timeoutSeconds: 5\n"
          + "    name: weblogic-server\n"
          + "    ports:\n"
          + "    - containerPort: 7001\n"
          + "      name: default\n"
          + "      protocol: TCP\n"
          + "    readinessProbe:\n"
          + "      failureThreshold: 1\n"
          + "      httpGet:\n"
          + "        path: /weblogic/ready\n"
          + "        port: 7001\n"
          + "      initialDelaySeconds: 1\n"
          + "      periodSeconds: 3\n"
          + "      timeoutSeconds: 2\n"
          + "    resources:\n"
          + "      limits: {}\n"
          + "      requests:\n"
          + "        memory: 768Mi\n"
          + "        cpu: 250m\n"
          + "    securityContext: {}\n"
          + "    volumeMounts:\n"
          + "    - mountPath: /weblogic-operator/scripts\n"
          + "      name: weblogic-scripts-cm-volume\n"
          + "      readOnly: true\n"
          + "    - mountPath: /weblogic-operator/debug\n"
          + "      name: weblogic-domain-debug-cm-volume\n"
          + "      readOnly: true\n"
          + "    - mountPath: /weblogic-operator/introspector\n"
          + "      name: weblogic-domain-introspect-cm-volume\n"
          + "    - mountPath: /auxiliary\n"
          + "      name: compatibility-mode-aux-image-volume-auxiliaryimagevolume1\n"
          + "  hostname: uid1-admin-server\n"
          + "  imagePullSecrets: []\n"
          + "  initContainers:\n"
          + "  - command:\n"
          + "    - /weblogic-operator/scripts/auxImage.sh\n"
          + "    env:\n"
          + "    - name: AUXILIARY_IMAGE_PATH\n"
          + "      value: /auxiliary\n"
          + "    - name: AUXILIARY_IMAGE_TARGET_PATH\n"
          + "      value: /tmpAuxiliaryImage\n"
          + "    - name: AUXILIARY_IMAGE_COMMAND\n"
          + "      value: cp -R $AUXILIARY_IMAGE_PATH/* $AUXILIARY_IMAGE_TARGET_PATH\n"
          + "    - name: AUXILIARY_IMAGE_CONTAINER_IMAGE\n"
          + "      value: model-in-image:WLS-AI-v1\n"
          + "    - name: AUXILIARY_IMAGE_CONTAINER_NAME\n"
          + "      value: compatibility-mode-operator-aux-container1\n"
          + "    image: model-in-image:WLS-AI-v1\n"
          + "    imagePullPolicy: IfNotPresent\n"
          + "    name: compatibility-mode-operator-aux-container1\n"
          + "    volumeMounts:\n"
          + "    - mountPath: /tmpAuxiliaryImage\n"
          + "      name: compatibility-mode-aux-image-volume-auxiliaryimagevolume1\n"
          + "    - mountPath: /weblogic-operator/scripts\n"
          + "      name: weblogic-scripts-cm-volume\n"
          + "  nodeSelector: {}\n"
          + "  securityContext: {}\n"
          + "  volumes:\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: weblogic-scripts-cm\n"
          + "    name: weblogic-scripts-cm-volume\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: uid1-weblogic-domain-debug-cm\n"
          + "      optional: true\n"
          + "    name: weblogic-domain-debug-cm-volume\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: uid1-weblogic-domain-introspect-cm\n"
          + "    name: weblogic-domain-introspect-cm-volume\n"
          + "  - emptyDir: {}\n"
          + "    name: compatibility-mode-aux-image-volume-auxiliaryimagevolume1\n";

  static final String MANAGED_MII_CONVERTED_AUX_IMAGE_POD_3_4 =
      "metadata:\n"
          + "  annotations:\n"
          + "    prometheus.io/path: /wls-exporter/metrics\n"
          + "    prometheus.io/port: '7001'\n"
          + "    prometheus.io/scrape: 'true'\n"
          + "    weblogic.sha256: dd443de3a2e4697415779dbd82161b8b1aede23a5bedb338f80a84adb4d9bfff\n"
          + "  labels:\n"
          + "    weblogic.domainName: domain1\n"
          + "    weblogic.serverName: ess_server1\n"
          + "    weblogic.domainRestartVersion: null\n"
          + "    weblogic.domainUID: uid1\n"
          + "    weblogic.createdByOperator: 'true'\n"
          + "    weblogic.operatorVersion: 3.4.0\n"
          + "    weblogic.clusterRestartVersion: null\n"
          + "    weblogic.serverRestartVersion: null\n"
          + "  name: uid1-ess-server1\n"
          + "  namespace: namespace\n"
          + "spec:\n"
          + "  containers:\n"
          + "  - command:\n"
          + "    - /weblogic-operator/scripts/startServer.sh\n"
          + "    env:\n"
          + "    - name: DOMAIN_NAME\n"
          + "      value: domain1\n"
          + "    - name: DOMAIN_HOME\n"
          + "      value: /u01/oracle/user_projects/domains\n"
          + "    - name: ADMIN_NAME\n"
          + "      value: ADMIN_SERVER\n"
          + "    - name: ADMIN_PORT\n"
          + "      value: '7001'\n"
          + "    - name: SERVER_NAME\n"
          + "      value: ess_server1\n"
          + "    - name: DOMAIN_UID\n"
          + "      value: uid1\n"
          + "    - name: NODEMGR_HOME\n"
          + "      value: /u01/nodemanager\n"
          + "    - name: LOG_HOME\n"
          + "    - name: SERVER_OUT_IN_POD_LOG\n"
          + "      value: 'true'\n"
          + "    - name: SERVICE_NAME\n"
          + "      value: uid1-ess-server1\n"
          + "    - name: AS_SERVICE_NAME\n"
          + "      value: uid1-admin-server\n"
          + "    - name: USER_MEM_ARGS\n"
          + "      value: -Djava.security.egd=file:/dev/./urandom\n"
          + "    - name: WDT_INSTALL_HOME\n"
          + "      value: /auxiliary/weblogic-deploy\n"
          + "    - name: WDT_MODEL_HOME\n"
          + "      value: /auxiliary/models\n"
          + "    - name: AUXILIARY_IMAGE_PATHS\n"
          + "      value: /auxiliary\n"
          + "    - name: ADMIN_USERNAME\n"
          + "    - name: ADMIN_PASSWORD\n"
          + "    image: image:latest\n"
          + "    imagePullPolicy: Always\n"
          + "    lifecycle:\n"
          + "      preStop:\n"
          + "        exec:\n"
          + "          command:\n"
          + "          - /weblogic-operator/scripts/stopServer.sh\n"
          + "    livenessProbe:\n"
          + "      exec:\n"
          + "        command:\n"
          + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
          + "      failureThreshold: 1\n"
          + "      initialDelaySeconds: 4\n"
          + "      periodSeconds: 6\n"
          + "      timeoutSeconds: 5\n"
          + "    name: weblogic-server\n"
          + "    ports:\n"
          + "    - containerPort: 8001\n"
          + "      name: default\n"
          + "      protocol: TCP\n"
          + "    readinessProbe:\n"
          + "      failureThreshold: 1\n"
          + "      httpGet:\n"
          + "        path: /weblogic/ready\n"
          + "        port: 8001\n"
          + "      initialDelaySeconds: 1\n"
          + "      periodSeconds: 3\n"
          + "      timeoutSeconds: 2\n"
          + "    resources:\n"
          + "      limits: {}\n"
          + "      requests:\n"
          + "        memory: 768Mi\n"
          + "        cpu: 250m\n"
          + "    securityContext: {}\n"
          + "    volumeMounts:\n"
          + "    - mountPath: /weblogic-operator/scripts\n"
          + "      name: weblogic-scripts-cm-volume\n"
          + "      readOnly: true\n"
          + "    - mountPath: /weblogic-operator/debug\n"
          + "      name: weblogic-domain-debug-cm-volume\n"
          + "      readOnly: true\n"
          + "    - mountPath: /weblogic-operator/introspector\n"
          + "      name: weblogic-domain-introspect-cm-volume\n"
          + "    - mountPath: /auxiliary\n"
          + "      name: compatibility-mode-aux-image-volume-auxiliaryimagevolume1\n"
          + "  imagePullSecrets: []\n"
          + "  initContainers:\n"
          + "  - command:\n"
          + "    - /weblogic-operator/scripts/auxImage.sh\n"
          + "    env:\n"
          + "    - name: AUXILIARY_IMAGE_PATH\n"
          + "      value: /auxiliary\n"
          + "    - name: AUXILIARY_IMAGE_TARGET_PATH\n"
          + "      value: /tmpAuxiliaryImage\n"
          + "    - name: AUXILIARY_IMAGE_COMMAND\n"
          + "      value: cp -R $AUXILIARY_IMAGE_PATH/* $AUXILIARY_IMAGE_TARGET_PATH\n"
          + "    - name: AUXILIARY_IMAGE_CONTAINER_IMAGE\n"
          + "      value: model-in-image:WLS-AI-v1\n"
          + "    - name: AUXILIARY_IMAGE_CONTAINER_NAME\n"
          + "      value: compatibility-mode-operator-aux-container1\n"
          + "    image: model-in-image:WLS-AI-v1\n"
          + "    imagePullPolicy: IfNotPresent\n"
          + "    name: compatibility-mode-operator-aux-container1\n"
          + "    volumeMounts:\n"
          + "    - mountPath: /tmpAuxiliaryImage\n"
          + "      name: aux-image-volume-auxiliaryimagevolume1\n"
          + "    - mountPath: /weblogic-operator/scripts\n"
          + "      name: weblogic-scripts-cm-volume\n"
          + "  nodeSelector: {}\n"
          + "  securityContext: {}\n"
          + "  volumes:\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: weblogic-scripts-cm\n"
          + "    name: weblogic-scripts-cm-volume\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: uid1-weblogic-domain-debug-cm\n"
          + "      optional: true\n"
          + "    name: weblogic-domain-debug-cm-volume\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: uid1-weblogic-domain-introspect-cm\n"
          + "    name: weblogic-domain-introspect-cm-volume\n"
          + "  - emptyDir: {}\n"
          + "    name: compatibility-mode-aux-image-volume-auxiliaryimagevolume1\n";

  static final String ADMIN_ISTIO_MONITORING_EXPORTER_TCP_PROTOCOL =
      "metadata:\n"
          + "  annotations:\n"
          + "    prometheus.io/path: /metrics\n"
          + "    prometheus.io/port: '8080'\n"
          + "    prometheus.io/scrape: 'true'\n"
          + "    weblogic.sha256: b135838901929f55b769e8e37abd133512ed8405ef8081be833e5ba00a203b7a\n"
          + "  labels:\n"
          + "    weblogic.operatorVersion: 3.4.0\n"
          + "    weblogic.domainName: domain1\n"
          + "    weblogic.serverName: ADMIN_SERVER\n"
          + "    weblogic.domainRestartVersion: null\n"
          + "    weblogic.domainUID: uid1\n"
          + "    weblogic.createdByOperator: 'true'\n"
          + "    weblogic.clusterRestartVersion: null\n"
          + "    weblogic.serverRestartVersion: null\n"
          + "  name: uid1-admin-server\n"
          + "  namespace: namespace\n"
          + "spec:\n"
          + "  containers:\n"
          + "  - env:\n"
          + "    - name: JAVA_OPTS\n"
          + "      value: -DDOMAIN=uid1 -DWLS_PORT=7001\n"
          + "    image: monexp:latest\n"
          + "    imagePullPolicy: Always\n"
          + "    name: monitoring-exporter\n"
          + "    ports:\n"
          + "    - containerPort: 8080\n"
          + "      name: tcp-metrics\n"
          + "      protocol: TCP\n"
          + "  - command:\n"
          + "    - /weblogic-operator/scripts/startServer.sh\n"
          + "    env:\n"
          + "    - name: DOMAIN_NAME\n"
          + "      value: domain1\n"
          + "    - name: DOMAIN_HOME\n"
          + "      value: /u01/oracle/user_projects/domains\n"
          + "    - name: ADMIN_NAME\n"
          + "      value: ADMIN_SERVER\n"
          + "    - name: ADMIN_PORT\n"
          + "      value: '7001'\n"
          + "    - name: SERVER_NAME\n"
          + "      value: ADMIN_SERVER\n"
          + "    - name: DOMAIN_UID\n"
          + "      value: uid1\n"
          + "    - name: NODEMGR_HOME\n"
          + "      value: /u01/nodemanager\n"
          + "    - name: LOG_HOME\n"
          + "    - name: SERVER_OUT_IN_POD_LOG\n"
          + "      value: 'true'\n"
          + "    - name: SERVICE_NAME\n"
          + "      value: uid1-admin-server\n"
          + "    - name: AS_SERVICE_NAME\n"
          + "      value: uid1-admin-server\n"
          + "    - name: USER_MEM_ARGS\n"
          + "      value: -Djava.security.egd=file:/dev/./urandom\n"
          + "    - name: ADMIN_USERNAME\n"
          + "    - name: ADMIN_PASSWORD\n"
          + "    - name: LOCAL_ADMIN_PORT\n"
          + "      value: '7001'\n"
          + "    - name: LOCAL_ADMIN_PROTOCOL\n"
          + "      value: t3\n"
          + "    - name: SHUTDOWN_TYPE\n"
          + "      value: Graceful\n"
          + "    - name: SHUTDOWN_TIMEOUT\n"
          + "      value: '30'\n"
          + "    - name: SHUTDOWN_IGNORE_SESSIONS\n"
          + "      value: 'false'\n"
          + "    - name: DYNAMIC_CONFIG_OVERRIDE\n"
          + "      value: 'true'\n"
          + "    - name: DOMAIN_SOURCE_TYPE\n"
          + "      value: Image\n"
          + "    - name: INTERNAL_OPERATOR_CERT\n"
          + "      value: encoded-cert-data\n"
          + "    image: image:latest\n"
          + "    imagePullPolicy: Always\n"
          + "    lifecycle:\n"
          + "      preStop:\n"
          + "        exec:\n"
          + "          command:\n"
          + "          - /weblogic-operator/scripts/stopServer.sh\n"
          + "    livenessProbe:\n"
          + "      exec:\n"
          + "        command:\n"
          + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
          + "      failureThreshold: 1\n"
          + "      initialDelaySeconds: 4\n"
          + "      periodSeconds: 6\n"
          + "      timeoutSeconds: 5\n"
          + "    name: weblogic-server\n"
          + "    ports:\n"
          + "    - containerPort: 31400\n"
          + "      name: tcp-t3channel\n"
          + "      protocol: TCP\n"
          + "    - containerPort: 7001\n"
          + "      name: tcp-ldap\n"
          + "      protocol: TCP\n"
          + "    - containerPort: 7001\n"
          + "      name: tcp-default\n"
          + "      protocol: TCP\n"
          + "    - containerPort: 7001\n"
          + "      name: http-default\n"
          + "      protocol: TCP\n"
          + "    - containerPort: 7001\n"
          + "      name: tcp-snmp\n"
          + "      protocol: TCP\n"
          + "    - containerPort: 7001\n"
          + "      name: tcp-iiop\n"
          + "      protocol: TCP\n"
          + "    readinessProbe:\n"
          + "      failureThreshold: 1\n"
          + "      httpGet:\n"
          + "        path: /weblogic/ready\n"
          + "        port: 8888\n"
          + "      initialDelaySeconds: 1\n"
          + "      periodSeconds: 3\n"
          + "      timeoutSeconds: 2\n"
          + "    resources:\n"
          + "      limits: {}\n"
          + "      requests: {}\n"
          + "    securityContext: {}\n"
          + "    volumeMounts:\n"
          + "    - mountPath: /weblogic-operator/scripts\n"
          + "      name: weblogic-scripts-cm-volume\n"
          + "      readOnly: true\n"
          + "    - mountPath: /weblogic-operator/debug\n"
          + "      name: weblogic-domain-debug-cm-volume\n"
          + "      readOnly: true\n"
          + "    - mountPath: /weblogic-operator/introspector\n"
          + "      name: weblogic-domain-introspect-cm-volume\n"
          + "  hostname: uid1-admin-server\n"
          + "  imagePullSecrets: []\n"
          + "  initContainers: []\n"
          + "  nodeSelector: {}\n"
          + "  securityContext: {}\n"
          + "  terminationGracePeriodSeconds: 40\n"
          + "  volumes:\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: weblogic-scripts-cm\n"
          + "    name: weblogic-scripts-cm-volume\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: uid1-weblogic-domain-debug-cm\n"
          + "      optional: true\n"
          + "    name: weblogic-domain-debug-cm-volume\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: uid1-weblogic-domain-introspect-cm\n"
          + "    name: weblogic-domain-introspect-cm-volume\n";

  static final String MANAGED_ISTIO_MONITORING_EXPORTER_TCP_PROTOCOL =
      "metadata:\n"
          + "  annotations:\n"
          + "    prometheus.io/path: /metrics\n"
          + "    prometheus.io/port: '8080'\n"
          + "    prometheus.io/scrape: 'true'\n"
          + "    weblogic.sha256: 73236318f8ab4a64e30bb2844c47437834dcedd7b6c962aa4c15c2f56cfcee4f\n"
          + "  labels:\n"
          + "    weblogic.operatorVersion: 3.4.0\n"
          + "    weblogic.domainName: domain1\n"
          + "    weblogic.serverName: ess_server1\n"
          + "    weblogic.domainRestartVersion: null\n"
          + "    weblogic.domainUID: uid1\n"
          + "    weblogic.createdByOperator: 'true'\n"
          + "    weblogic.clusterRestartVersion: null\n"
          + "    weblogic.serverRestartVersion: null\n"
          + "  name: uid1-ess-server1\n"
          + "  namespace: namespace\n"
          + "spec:\n"
          + "  containers:\n"
          + "  - env:\n"
          + "    - name: JAVA_OPTS\n"
          + "      value: -DDOMAIN=uid1 -DWLS_PORT=8001\n"
          + "    image: monexp:latest\n"
          + "    imagePullPolicy: Always\n"
          + "    name: monitoring-exporter\n"
          + "    ports:\n"
          + "    - containerPort: 8080\n"
          + "      name: tcp-metrics\n"
          + "      protocol: TCP\n"
          + "  - command:\n"
          + "    - /weblogic-operator/scripts/startServer.sh\n"
          + "    env:\n"
          + "    - name: DOMAIN_NAME\n"
          + "      value: domain1\n"
          + "    - name: DOMAIN_HOME\n"
          + "      value: /u01/oracle/user_projects/domains\n"
          + "    - name: ADMIN_NAME\n"
          + "      value: ADMIN_SERVER\n"
          + "    - name: ADMIN_PORT\n"
          + "      value: '7001'\n"
          + "    - name: SERVER_NAME\n"
          + "      value: ess_server1\n"
          + "    - name: DOMAIN_UID\n"
          + "      value: uid1\n"
          + "    - name: NODEMGR_HOME\n"
          + "      value: /u01/nodemanager\n"
          + "    - name: LOG_HOME\n"
          + "    - name: SERVER_OUT_IN_POD_LOG\n"
          + "      value: 'true'\n"
          + "    - name: SERVICE_NAME\n"
          + "      value: uid1-ess-server1\n"
          + "    - name: AS_SERVICE_NAME\n"
          + "      value: uid1-admin-server\n"
          + "    - name: USER_MEM_ARGS\n"
          + "      value: -Djava.security.egd=file:/dev/./urandom\n"
          + "    - name: ADMIN_USERNAME\n"
          + "    - name: ADMIN_PASSWORD\n"
          + "    - name: LOCAL_ADMIN_PORT\n"
          + "      value: '8001'\n"
          + "    - name: LOCAL_ADMIN_PROTOCOL\n"
          + "      value: t3\n"
          + "    - name: SHUTDOWN_TYPE\n"
          + "      value: Graceful\n"
          + "    - name: SHUTDOWN_TIMEOUT\n"
          + "      value: '30'\n"
          + "    - name: SHUTDOWN_IGNORE_SESSIONS\n"
          + "      value: 'false'\n"
          + "    - name: DYNAMIC_CONFIG_OVERRIDE\n"
          + "      value: 'true'\n"
          + "    - name: DOMAIN_SOURCE_TYPE\n"
          + "      value: Image\n"
          + "    image: image:latest\n"
          + "    imagePullPolicy: Always\n"
          + "    lifecycle:\n"
          + "      preStop:\n"
          + "        exec:\n"
          + "          command:\n"
          + "          - /weblogic-operator/scripts/stopServer.sh\n"
          + "    livenessProbe:\n"
          + "      exec:\n"
          + "        command:\n"
          + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
          + "      failureThreshold: 1\n"
          + "      initialDelaySeconds: 4\n"
          + "      periodSeconds: 6\n"
          + "      timeoutSeconds: 5\n"
          + "    name: weblogic-server\n"
          + "    ports:\n"
          + "    - containerPort: 31400\n"
          + "      name: tcp-t3channel\n"
          + "      protocol: TCP\n"
          + "    - containerPort: 7001\n"
          + "      name: tcp-ldap\n"
          + "      protocol: TCP\n"
          + "    - containerPort: 7102\n"
          + "      name: tls-ldaps\n"
          + "      protocol: TCP\n"
          + "    - containerPort: 7001\n"
          + "      name: tcp-default\n"
          + "      protocol: TCP\n"
          + "    - containerPort: 7102\n"
          + "      name: tls-default\n"
          + "      protocol: TCP\n"
          + "    - containerPort: 7001\n"
          + "      name: http-default\n"
          + "      protocol: TCP\n"
          + "    - containerPort: 7102\n"
          + "      name: https-secure\n"
          + "      protocol: TCP\n"
          + "    - containerPort: 7001\n"
          + "      name: tcp-snmp\n"
          + "      protocol: TCP\n"
          + "    - containerPort: 7001\n"
          + "      name: tcp-iiop\n"
          + "      protocol: TCP\n"
          + "    - containerPort: 7102\n"
          + "      name: tls-iiops\n"
          + "      protocol: TCP\n"
          + "    readinessProbe:\n"
          + "      failureThreshold: 1\n"
          + "      httpGet:\n"
          + "        path: /weblogic/ready\n"
          + "        port: 8888\n"
          + "      initialDelaySeconds: 1\n"
          + "      periodSeconds: 3\n"
          + "      timeoutSeconds: 2\n"
          + "    resources:\n"
          + "      limits: {}\n"
          + "      requests: {}\n"
          + "    securityContext: {}\n"
          + "    volumeMounts:\n"
          + "    - mountPath: /weblogic-operator/scripts\n"
          + "      name: weblogic-scripts-cm-volume\n"
          + "      readOnly: true\n"
          + "    - mountPath: /weblogic-operator/debug\n"
          + "      name: weblogic-domain-debug-cm-volume\n"
          + "      readOnly: true\n"
          + "    - mountPath: /weblogic-operator/introspector\n"
          + "      name: weblogic-domain-introspect-cm-volume\n"
          + "  imagePullSecrets: []\n"
          + "  initContainers: []\n"
          + "  nodeSelector: {}\n"
          + "  securityContext: {}\n"
          + "  terminationGracePeriodSeconds: 40\n"
          + "  volumes:\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: weblogic-scripts-cm\n"
          + "    name: weblogic-scripts-cm-volume\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: uid1-weblogic-domain-debug-cm\n"
          + "      optional: true\n"
          + "    name: weblogic-domain-debug-cm-volume\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: uid1-weblogic-domain-introspect-cm\n"
          + "    name: weblogic-domain-introspect-cm-volume\n";

  static final String ADMIN_MII_CONVERTED_AUX_IMAGE_POD_3_4_1 =
      "metadata:\n"
          + "  annotations:\n"
          + "    prometheus.io/path: /wls-exporter/metrics\n"
          + "    prometheus.io/port: '7001'\n"
          + "    prometheus.io/scrape: 'true'\n"
          + "    weblogic.sha256: 0f0b7e89b18c78476eb8525672e18af7c438871786fe916e7a7062037cbf8140\n"
          + "  labels:\n"
          + "    weblogic.domainName: domain1\n"
          + "    weblogic.serverName: ADMIN_SERVER\n"
          + "    weblogic.domainRestartVersion: null\n"
          + "    weblogic.domainUID: uid1\n"
          + "    weblogic.createdByOperator: 'true'\n"
          + "    weblogic.operatorVersion: 3.4.1\n"
          + "    weblogic.clusterRestartVersion: null\n"
          + "    weblogic.serverRestartVersion: null\n"
          + "  name: uid1-admin-server\n"
          + "  namespace: namespace\n"
          + "spec:\n"
          + "  containers:\n"
          + "  - command:\n"
          + "    - /weblogic-operator/scripts/startServer.sh\n"
          + "    env:\n"
          + "    - name: DOMAIN_NAME\n"
          + "      value: domain1\n"
          + "    - name: DOMAIN_HOME\n"
          + "      value: /u01/oracle/user_projects/domains\n"
          + "    - name: ADMIN_NAME\n"
          + "      value: ADMIN_SERVER\n"
          + "    - name: ADMIN_PORT\n"
          + "      value: '7001'\n"
          + "    - name: SERVER_NAME\n"
          + "      value: ADMIN_SERVER\n"
          + "    - name: DOMAIN_UID\n"
          + "      value: uid1\n"
          + "    - name: NODEMGR_HOME\n"
          + "      value: /u01/nodemanager\n"
          + "    - name: LOG_HOME\n"
          + "    - name: SERVER_OUT_IN_POD_LOG\n"
          + "      value: 'true'\n"
          + "    - name: SERVICE_NAME\n"
          + "      value: uid1-admin-server\n"
          + "    - name: AS_SERVICE_NAME\n"
          + "      value: uid1-admin-server\n"
          + "    - name: USER_MEM_ARGS\n"
          + "      value: -Djava.security.egd=file:/dev/./urandom\n"
          + "    - name: WDT_INSTALL_HOME\n"
          + "      value: /auxiliary/weblogic-deploy\n"
          + "    - name: WDT_MODEL_HOME\n"
          + "      value: /auxiliary/models\n"
          + "    - name: AUXILIARY_IMAGE_PATHS\n"
          + "      value: /auxiliary\n"
          + "    - name: ADMIN_USERNAME\n"
          + "    - name: ADMIN_PASSWORD\n"
          + "    image: image:latest\n"
          + "    imagePullPolicy: Always\n"
          + "    lifecycle:\n"
          + "      preStop:\n"
          + "        exec:\n"
          + "          command:\n"
          + "          - /weblogic-operator/scripts/stopServer.sh\n"
          + "    livenessProbe:\n"
          + "      exec:\n"
          + "        command:\n"
          + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
          + "      failureThreshold: 1\n"
          + "      initialDelaySeconds: 4\n"
          + "      periodSeconds: 6\n"
          + "      timeoutSeconds: 5\n"
          + "    name: weblogic-server\n"
          + "    ports:\n"
          + "    - containerPort: 7001\n"
          + "      name: default\n"
          + "      protocol: TCP\n"
          + "    readinessProbe:\n"
          + "      failureThreshold: 1\n"
          + "      httpGet:\n"
          + "        path: /weblogic/ready\n"
          + "        port: 7001\n"
          + "      initialDelaySeconds: 1\n"
          + "      periodSeconds: 3\n"
          + "      timeoutSeconds: 2\n"
          + "    resources:\n"
          + "      limits: {}\n"
          + "      requests:\n"
          + "        memory: 768Mi\n"
          + "        cpu: 250m\n"
          + "    securityContext: {}\n"
          + "    volumeMounts:\n"
          + "    - mountPath: /weblogic-operator/scripts\n"
          + "      name: weblogic-scripts-cm-volume\n"
          + "      readOnly: true\n"
          + "    - mountPath: /weblogic-operator/debug\n"
          + "      name: weblogic-domain-debug-cm-volume\n"
          + "      readOnly: true\n"
          + "    - mountPath: /weblogic-operator/introspector\n"
          + "      name: weblogic-domain-introspect-cm-volume\n"
          + "    - mountPath: /auxiliary\n"
          + "      name: compatibility-mode-aux-image-volume-auxiliaryimagevolume1\n"
          + "  hostname: uid1-admin-server\n"
          + "  imagePullSecrets: []\n"
          + "  initContainers:\n"
          + "  - command:\n"
          + "    - /weblogic-operator/scripts/auxImage.sh\n"
          + "    env:\n"
          + "    - name: AUXILIARY_IMAGE_PATH\n"
          + "      value: /auxiliary\n"
          + "    - name: AUXILIARY_IMAGE_TARGET_PATH\n"
          + "      value: /tmpAuxiliaryImage\n"
          + "    - name: AUXILIARY_IMAGE_COMMAND\n"
          + "      value: cp -R $AUXILIARY_IMAGE_PATH/* $AUXILIARY_IMAGE_TARGET_PATH\n"
          + "    - name: AUXILIARY_IMAGE_CONTAINER_IMAGE\n"
          + "      value: model-in-image:WLS-AI-v1\n"
          + "    - name: AUXILIARY_IMAGE_CONTAINER_NAME\n"
          + "      value: compatibility-mode-operator-aux-container1\n"
          + "    image: model-in-image:WLS-AI-v1\n"
          + "    imagePullPolicy: IfNotPresent\n"
          + "    name: compatibility-mode-operator-aux-container1\n"
          + "    resources:\n"
          + "      limits: {}\n"
          + "      requests:\n"
          + "        memory: 768Mi\n"
          + "        cpu: 250m\n"
          + "    volumeMounts:\n"
          + "    - mountPath: /tmpAuxiliaryImage\n"
          + "      name: compatibility-mode-aux-image-volume-auxiliaryimagevolume1\n"
          + "    - mountPath: /weblogic-operator/scripts\n"
          + "      name: weblogic-scripts-cm-volume\n"
          + "  nodeSelector: {}\n"
          + "  securityContext: {}\n"
          + "  volumes:\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: weblogic-scripts-cm\n"
          + "    name: weblogic-scripts-cm-volume\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: uid1-weblogic-domain-debug-cm\n"
          + "      optional: true\n"
          + "    name: weblogic-domain-debug-cm-volume\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: uid1-weblogic-domain-introspect-cm\n"
          + "    name: weblogic-domain-introspect-cm-volume\n"
          + "  - emptyDir: {}\n"
          + "    name: compatibility-mode-aux-image-volume-auxiliaryimagevolume1\n";

  static final String MANAGED_MII_CONVERTED_AUX_IMAGE_POD_3_4_1 =
      "metadata:\n"
          + "  annotations:\n"
          + "    prometheus.io/path: /wls-exporter/metrics\n"
          + "    prometheus.io/port: '7001'\n"
          + "    prometheus.io/scrape: 'true'\n"
          + "    weblogic.sha256: 49a8eea3c4ab938419706bdd2c267ae9e6603656e1b096900fe4f8e7535fc980\n"
          + "  labels:\n"
          + "    weblogic.domainName: domain1\n"
          + "    weblogic.serverName: ess_server1\n"
          + "    weblogic.domainRestartVersion: null\n"
          + "    weblogic.domainUID: uid1\n"
          + "    weblogic.createdByOperator: 'true'\n"
          + "    weblogic.operatorVersion: 3.4.1\n"
          + "    weblogic.clusterRestartVersion: null\n"
          + "    weblogic.serverRestartVersion: null\n"
          + "  name: uid1-ess-server1\n"
          + "  namespace: namespace\n"
          + "spec:\n"
          + "  containers:\n"
          + "  - command:\n"
          + "    - /weblogic-operator/scripts/startServer.sh\n"
          + "    env:\n"
          + "    - name: DOMAIN_NAME\n"
          + "      value: domain1\n"
          + "    - name: DOMAIN_HOME\n"
          + "      value: /u01/oracle/user_projects/domains\n"
          + "    - name: ADMIN_NAME\n"
          + "      value: ADMIN_SERVER\n"
          + "    - name: ADMIN_PORT\n"
          + "      value: '7001'\n"
          + "    - name: SERVER_NAME\n"
          + "      value: ess_server1\n"
          + "    - name: DOMAIN_UID\n"
          + "      value: uid1\n"
          + "    - name: NODEMGR_HOME\n"
          + "      value: /u01/nodemanager\n"
          + "    - name: LOG_HOME\n"
          + "    - name: SERVER_OUT_IN_POD_LOG\n"
          + "      value: 'true'\n"
          + "    - name: SERVICE_NAME\n"
          + "      value: uid1-ess-server1\n"
          + "    - name: AS_SERVICE_NAME\n"
          + "      value: uid1-admin-server\n"
          + "    - name: USER_MEM_ARGS\n"
          + "      value: -Djava.security.egd=file:/dev/./urandom\n"
          + "    - name: WDT_INSTALL_HOME\n"
          + "      value: /auxiliary/weblogic-deploy\n"
          + "    - name: WDT_MODEL_HOME\n"
          + "      value: /auxiliary/models\n"
          + "    - name: AUXILIARY_IMAGE_PATHS\n"
          + "      value: /auxiliary\n"
          + "    - name: ADMIN_USERNAME\n"
          + "    - name: ADMIN_PASSWORD\n"
          + "    image: image:latest\n"
          + "    imagePullPolicy: Always\n"
          + "    lifecycle:\n"
          + "      preStop:\n"
          + "        exec:\n"
          + "          command:\n"
          + "          - /weblogic-operator/scripts/stopServer.sh\n"
          + "    livenessProbe:\n"
          + "      exec:\n"
          + "        command:\n"
          + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
          + "      failureThreshold: 1\n"
          + "      initialDelaySeconds: 4\n"
          + "      periodSeconds: 6\n"
          + "      timeoutSeconds: 5\n"
          + "    name: weblogic-server\n"
          + "    ports:\n"
          + "    - containerPort: 8001\n"
          + "      name: default\n"
          + "      protocol: TCP\n"
          + "    readinessProbe:\n"
          + "      failureThreshold: 1\n"
          + "      httpGet:\n"
          + "        path: /weblogic/ready\n"
          + "        port: 8001\n"
          + "      initialDelaySeconds: 1\n"
          + "      periodSeconds: 3\n"
          + "      timeoutSeconds: 2\n"
          + "    resources:\n"
          + "      limits: {}\n"
          + "      requests:\n"
          + "        memory: 768Mi\n"
          + "        cpu: 250m\n"
          + "    securityContext: {}\n"
          + "    volumeMounts:\n"
          + "    - mountPath: /weblogic-operator/scripts\n"
          + "      name: weblogic-scripts-cm-volume\n"
          + "      readOnly: true\n"
          + "    - mountPath: /weblogic-operator/debug\n"
          + "      name: weblogic-domain-debug-cm-volume\n"
          + "      readOnly: true\n"
          + "    - mountPath: /weblogic-operator/introspector\n"
          + "      name: weblogic-domain-introspect-cm-volume\n"
          + "    - mountPath: /auxiliary\n"
          + "      name: compatibility-mode-aux-image-volume-auxiliaryimagevolume1\n"
          + "  imagePullSecrets: []\n"
          + "  initContainers:\n"
          + "  - command:\n"
          + "    - /weblogic-operator/scripts/auxImage.sh\n"
          + "    env:\n"
          + "    - name: AUXILIARY_IMAGE_PATH\n"
          + "      value: /auxiliary\n"
          + "    - name: AUXILIARY_IMAGE_TARGET_PATH\n"
          + "      value: /tmpAuxiliaryImage\n"
          + "    - name: AUXILIARY_IMAGE_COMMAND\n"
          + "      value: cp -R $AUXILIARY_IMAGE_PATH/* $AUXILIARY_IMAGE_TARGET_PATH\n"
          + "    - name: AUXILIARY_IMAGE_CONTAINER_IMAGE\n"
          + "      value: model-in-image:WLS-AI-v1\n"
          + "    - name: AUXILIARY_IMAGE_CONTAINER_NAME\n"
          + "      value: compatibility-mode-operator-aux-container1\n"
          + "    image: model-in-image:WLS-AI-v1\n"
          + "    imagePullPolicy: IfNotPresent\n"
          + "    name: compatibility-mode-operator-aux-container1\n"
          + "    resources:\n"
          + "      limits: {}\n"
          + "      requests:\n"
          + "        memory: 768Mi\n"
          + "        cpu: 250m\n"
          + "    volumeMounts:\n"
          + "    - mountPath: /tmpAuxiliaryImage\n"
          + "      name: aux-image-volume-auxiliaryimagevolume1\n"
          + "    - mountPath: /weblogic-operator/scripts\n"
          + "      name: weblogic-scripts-cm-volume\n"
          + "  nodeSelector: {}\n"
          + "  securityContext: {}\n"
          + "  volumes:\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: weblogic-scripts-cm\n"
          + "    name: weblogic-scripts-cm-volume\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: uid1-weblogic-domain-debug-cm\n"
          + "      optional: true\n"
          + "    name: weblogic-domain-debug-cm-volume\n"
          + "  - configMap:\n"
          + "      defaultMode: 365\n"
          + "      name: uid1-weblogic-domain-introspect-cm\n"
          + "    name: weblogic-domain-introspect-cm-volume\n"
          + "  - emptyDir: {}\n"
          + "    name: compatibility-mode-aux-image-volume-auxiliaryimagevolume1\n";
}
