// Copyright (c) 2021, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

package oracle.kubernetes.operator.helpers;

/**
 * To present pods from rolling when a customer upgrades the operator, we must test against the YAML that would
 * be generated in old operator versions for the settings in the PodHelper test.
 *
 * The settings here are taken from 3.1.0.
 */
class ReferenceObjects {
  static final String MANAGED_PLAINPORT_POD_3_1 =
        "metadata:\n"
        + "  annotations:\n"
        + "    prometheus.io/path: /wls-exporter/metrics\n"
        + "    prometheus.io/port: '8001'\n"
        + "    prometheus.io/scrape: 'true'\n"
        + "    weblogic.sha256: 6e1c6a716a9e0078a56c2df86ffe1cd2f0f9bdbe271f169dc1d548d026aa52b7\n"
        + "  labels:\n"
        + "    weblogic.domainName: domain1\n"
        + "    weblogic.serverName: ess_server1\n"
        + "    weblogic.domainRestartVersion: null\n"
        + "    weblogic.domainUID: uid1\n"
        + "    weblogic.createdByOperator: 'true'\n"
        + "    weblogic.clusterRestartVersion: null\n"
        + "    weblogic.serverRestartVersion: null\n"
        + "  name: uid1-ess-server1\n"
        + "  namespace: namespace\n"
        + "spec:\n"
        + "  containers:\n"
        + "  - command:\n"
        + "    - /weblogic-operator/scripts/startServer.sh\n"
        + "    env:\n"
        + "    - name: DOMAIN_NAME\n"
        + "      value: domain1\n"
        + "    - name: DOMAIN_HOME\n"
        + "      value: /u01/oracle/user_projects/domains\n"
        + "    - name: ADMIN_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: ADMIN_PORT\n"
        + "      value: '7001'\n"
        + "    - name: SERVER_NAME\n"
        + "      value: ess_server1\n"
        + "    - name: DOMAIN_UID\n"
        + "      value: uid1\n"
        + "    - name: NODEMGR_HOME\n"
        + "      value: /u01/nodemanager\n"
        + "    - name: LOG_HOME\n"
        + "    - name: SERVER_OUT_IN_POD_LOG\n"
        + "      value: 'true'\n"
        + "    - name: SERVICE_NAME\n"
        + "      value: uid1-ess-server1\n"
        + "    - name: AS_SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: USER_MEM_ARGS\n"
        + "      value: -Djava.security.egd=file:/dev/./urandom\n"
        + "    - name: ADMIN_USERNAME\n"
        + "    - name: ADMIN_PASSWORD\n"
        + "    image: image:latest\n"
        + "    imagePullPolicy: Always\n"
        + "    lifecycle:\n"
        + "      preStop:\n"
        + "        exec:\n"
        + "          command:\n"
        + "          - /weblogic-operator/scripts/stopServer.sh\n"
        + "    livenessProbe:\n"
        + "      exec:\n"
        + "        command:\n"
        + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
        + "      failureThreshold: 1\n"
        + "      initialDelaySeconds: 4\n"
        + "      periodSeconds: 6\n"
        + "      timeoutSeconds: 5\n"
        + "    name: weblogic-server\n"
        + "    ports:\n"
        + "    - containerPort: 8001\n"
        + "      name: default\n"
        + "      protocol: TCP\n"
        + "    readinessProbe:\n"
        + "      failureThreshold: 1\n"
        + "      httpGet:\n"
        + "        path: /weblogic/ready\n"
        + "        port: 8001\n"
        + "      initialDelaySeconds: 1\n"
        + "      periodSeconds: 3\n"
        + "      timeoutSeconds: 2\n"
        + "    resources:\n"
        + "      limits: {}\n"
        + "      requests: {}\n"
        + "    securityContext: {}\n"
        + "    volumeMounts:\n"
        + "    - mountPath: /weblogic-operator/scripts\n"
        + "      name: weblogic-scripts-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/debug\n"
        + "      name: weblogic-domain-debug-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/introspector\n"
        + "      name: weblogic-domain-introspect-cm-volume\n"
        + "  imagePullSecrets: []\n"
        + "  initContainers: []\n"
        + "  nodeSelector: {}\n"
        + "  securityContext: {}\n"
        + "  volumes:\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: weblogic-scripts-cm\n"
        + "    name: weblogic-scripts-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-debug-cm\n"
        + "      optional: true\n"
        + "    name: weblogic-domain-debug-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-introspect-cm\n"
        + "    name: weblogic-domain-introspect-cm-volume\n";

  static final String ADMIN_PLAINPORT_POD_3_1
        = "metadata:\n"
        + "  annotations:\n"
        + "    prometheus.io/path: /wls-exporter/metrics\n"
        + "    prometheus.io/port: '7001'\n"
        + "    prometheus.io/scrape: 'true'\n"
        + "    weblogic.sha256: fc735cf7c34bc1492a237149c4e27c9bb27575de463dbc55e953588862098df4\n"
        + "  labels:\n"
        + "    weblogic.domainName: domain1\n"
        + "    weblogic.serverName: ADMIN_SERVER\n"
        + "    weblogic.domainRestartVersion: null\n"
        + "    weblogic.domainUID: uid1\n"
        + "    weblogic.createdByOperator: 'true'\n"
        + "    weblogic.clusterRestartVersion: null\n"
        + "    weblogic.serverRestartVersion: null\n"
        + "  name: uid1-admin-server\n"
        + "  namespace: namespace\n"
        + "spec:\n"
        + "  containers:\n"
        + "  - command:\n"
        + "    - /weblogic-operator/scripts/startServer.sh\n"
        + "    env:\n"
        + "    - name: DOMAIN_NAME\n"
        + "      value: domain1\n"
        + "    - name: DOMAIN_HOME\n"
        + "      value: /u01/oracle/user_projects/domains\n"
        + "    - name: ADMIN_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: ADMIN_PORT\n"
        + "      value: '7001'\n"
        + "    - name: SERVER_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: DOMAIN_UID\n"
        + "      value: uid1\n"
        + "    - name: NODEMGR_HOME\n"
        + "      value: /u01/nodemanager\n"
        + "    - name: LOG_HOME\n"
        + "    - name: SERVER_OUT_IN_POD_LOG\n"
        + "      value: 'true'\n"
        + "    - name: SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: AS_SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: USER_MEM_ARGS\n"
        + "      value: -Djava.security.egd=file:/dev/./urandom\n"
        + "    - name: ADMIN_USERNAME\n"
        + "    - name: ADMIN_PASSWORD\n"
        + "    image: image:latest\n"
        + "    imagePullPolicy: Always\n"
        + "    lifecycle:\n"
        + "      preStop:\n"
        + "        exec:\n"
        + "          command:\n"
        + "          - /weblogic-operator/scripts/stopServer.sh\n"
        + "    livenessProbe:\n"
        + "      exec:\n"
        + "        command:\n"
        + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
        + "      failureThreshold: 1\n"
        + "      initialDelaySeconds: 4\n"
        + "      periodSeconds: 6\n"
        + "      timeoutSeconds: 5\n"
        + "    name: weblogic-server\n"
        + "    ports:\n"
        + "    - containerPort: 7001\n"
        + "      name: default\n"
        + "      protocol: TCP\n"
        + "    readinessProbe:\n"
        + "      failureThreshold: 1\n"
        + "      httpGet:\n"
        + "        path: /weblogic/ready\n"
        + "        port: 7001\n"
        + "      initialDelaySeconds: 1\n"
        + "      periodSeconds: 3\n"
        + "      timeoutSeconds: 2\n"
        + "    resources:\n"
        + "      limits: {}\n"
        + "      requests: {}\n"
        + "    securityContext: {}\n"
        + "    volumeMounts:\n"
        + "    - mountPath: /weblogic-operator/scripts\n"
        + "      name: weblogic-scripts-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/debug\n"
        + "      name: weblogic-domain-debug-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/introspector\n"
        + "      name: weblogic-domain-introspect-cm-volume\n"
        + "  hostname: uid1-admin-server\n"
        + "  imagePullSecrets: []\n"
        + "  initContainers: []\n"
        + "  nodeSelector: {}\n"
        + "  securityContext: {}\n"
        + "  volumes:\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: weblogic-scripts-cm\n"
        + "    name: weblogic-scripts-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-debug-cm\n"
        + "      optional: true\n"
        + "    name: weblogic-domain-debug-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-introspect-cm\n"
        + "    name: weblogic-domain-introspect-cm-volume\n";

  static final String MANAGED_SSLPORT_POD_3_1 =
        "metadata:\n"
        + "  annotations:\n"
        + "    prometheus.io/path: /wls-exporter/metrics\n"
        + "    prometheus.io/port: '7002'\n"
        + "    prometheus.io/scrape: 'true'\n"
        + "    weblogic.sha256: 368b26eaf1645f966d4c350906b59a0afcc0fbdf9ed30779b71a6d044eb480dd\n"
        + "  labels:\n"
        + "    weblogic.domainName: domain1\n"
        + "    weblogic.serverName: ess_server1\n"
        + "    weblogic.domainRestartVersion: null\n"
        + "    weblogic.domainUID: uid1\n"
        + "    weblogic.createdByOperator: 'true'\n"
        + "    weblogic.clusterRestartVersion: null\n"
        + "    weblogic.serverRestartVersion: null\n"
        + "  name: uid1-ess-server1\n"
        + "  namespace: namespace\n"
        + "spec:\n"
        + "  containers:\n"
        + "  - command:\n"
        + "    - /weblogic-operator/scripts/startServer.sh\n"
        + "    env:\n"
        + "    - name: DOMAIN_NAME\n"
        + "      value: domain1\n"
        + "    - name: DOMAIN_HOME\n"
        + "      value: /u01/oracle/user_projects/domains\n"
        + "    - name: ADMIN_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: ADMIN_PORT\n"
        + "      value: '7001'\n"
        + "    - name: ADMIN_PORT_SECURE\n"
        + "      value: 'true'\n"
        + "    - name: SERVER_NAME\n"
        + "      value: ess_server1\n"
        + "    - name: DOMAIN_UID\n"
        + "      value: uid1\n"
        + "    - name: NODEMGR_HOME\n"
        + "      value: /u01/nodemanager\n"
        + "    - name: LOG_HOME\n"
        + "    - name: SERVER_OUT_IN_POD_LOG\n"
        + "      value: 'true'\n"
        + "    - name: SERVICE_NAME\n"
        + "      value: uid1-ess-server1\n"
        + "    - name: AS_SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: USER_MEM_ARGS\n"
        + "      value: -Djava.security.egd=file:/dev/./urandom\n"
        + "    - name: ADMIN_USERNAME\n"
        + "    - name: ADMIN_PASSWORD\n"
        + "    image: image:latest\n"
        + "    imagePullPolicy: Always\n"
        + "    lifecycle:\n"
        + "      preStop:\n"
        + "        exec:\n"
        + "          command:\n"
        + "          - /weblogic-operator/scripts/stopServer.sh\n"
        + "    livenessProbe:\n"
        + "      exec:\n"
        + "        command:\n"
        + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
        + "      failureThreshold: 1\n"
        + "      initialDelaySeconds: 4\n"
        + "      periodSeconds: 6\n"
        + "      timeoutSeconds: 5\n"
        + "    name: weblogic-server\n"
        + "    ports:\n"
        + "    - containerPort: 8001\n"
        + "      name: default\n"
        + "      protocol: TCP\n"
        + "    - containerPort: 7002\n"
        + "      name: default-secure\n"
        + "      protocol: TCP\n"
        + "    readinessProbe:\n"
        + "      failureThreshold: 1\n"
        + "      httpGet:\n"
        + "        path: /weblogic/ready\n"
        + "        port: 7002\n"
        + "        scheme: HTTPS\n"
        + "      initialDelaySeconds: 1\n"
        + "      periodSeconds: 3\n"
        + "      timeoutSeconds: 2\n"
        + "    resources:\n"
        + "      limits: {}\n"
        + "      requests: {}\n"
        + "    securityContext: {}\n"
        + "    volumeMounts:\n"
        + "    - mountPath: /weblogic-operator/scripts\n"
        + "      name: weblogic-scripts-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/debug\n"
        + "      name: weblogic-domain-debug-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/introspector\n"
        + "      name: weblogic-domain-introspect-cm-volume\n"
        + "  imagePullSecrets: []\n"
        + "  initContainers: []\n"
        + "  nodeSelector: {}\n"
        + "  securityContext: {}\n"
        + "  volumes:\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: weblogic-scripts-cm\n"
        + "    name: weblogic-scripts-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-debug-cm\n"
        + "      optional: true\n"
        + "    name: weblogic-domain-debug-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-introspect-cm\n"
        + "    name: weblogic-domain-introspect-cm-volume\n";

  static final String ADMIN_SSLPORT_POD_3_1 =
        "metadata:\n"
        + "  annotations:\n"
        + "    prometheus.io/path: /wls-exporter/metrics\n"
        + "    prometheus.io/port: '7002'\n"
        + "    prometheus.io/scrape: 'true'\n"
        + "    weblogic.sha256: 854c2ce0b646268a7e72f601f625a8466f45d71f7f635a65ad3740ecb9bdf39a\n"
        + "  labels:\n"
        + "    weblogic.domainName: domain1\n"
        + "    weblogic.serverName: ADMIN_SERVER\n"
        + "    weblogic.domainRestartVersion: null\n"
        + "    weblogic.domainUID: uid1\n"
        + "    weblogic.createdByOperator: 'true'\n"
        + "    weblogic.clusterRestartVersion: null\n"
        + "    weblogic.serverRestartVersion: null\n"
        + "  name: uid1-admin-server\n"
        + "  namespace: namespace\n"
        + "spec:\n"
        + "  containers:\n"
        + "  - command:\n"
        + "    - /weblogic-operator/scripts/startServer.sh\n"
        + "    env:\n"
        + "    - name: DOMAIN_NAME\n"
        + "      value: domain1\n"
        + "    - name: DOMAIN_HOME\n"
        + "      value: /u01/oracle/user_projects/domains\n"
        + "    - name: ADMIN_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: ADMIN_PORT\n"
        + "      value: '7002'\n"
        + "    - name: ADMIN_PORT_SECURE\n"
        + "      value: 'true'\n"
        + "    - name: ADMIN_SERVER_PORT_SECURE\n"
        + "      value: 'true'\n"
        + "    - name: SERVER_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: DOMAIN_UID\n"
        + "      value: uid1\n"
        + "    - name: NODEMGR_HOME\n"
        + "      value: /u01/nodemanager\n"
        + "    - name: LOG_HOME\n"
        + "    - name: SERVER_OUT_IN_POD_LOG\n"
        + "      value: 'true'\n"
        + "    - name: SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: AS_SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: USER_MEM_ARGS\n"
        + "      value: -Djava.security.egd=file:/dev/./urandom\n"
        + "    - name: ADMIN_USERNAME\n"
        + "    - name: ADMIN_PASSWORD\n"
        + "    image: image:latest\n"
        + "    imagePullPolicy: Always\n"
        + "    lifecycle:\n"
        + "      preStop:\n"
        + "        exec:\n"
        + "          command:\n"
        + "          - /weblogic-operator/scripts/stopServer.sh\n"
        + "    livenessProbe:\n"
        + "      exec:\n"
        + "        command:\n"
        + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
        + "      failureThreshold: 1\n"
        + "      initialDelaySeconds: 4\n"
        + "      periodSeconds: 6\n"
        + "      timeoutSeconds: 5\n"
        + "    name: weblogic-server\n"
        + "    ports:\n"
        + "    - containerPort: 7001\n"
        + "      name: default\n"
        + "      protocol: TCP\n"
        + "    - containerPort: 7002\n"
        + "      name: default-secure\n"
        + "      protocol: TCP\n"
        + "    readinessProbe:\n"
        + "      failureThreshold: 1\n"
        + "      httpGet:\n"
        + "        path: /weblogic/ready\n"
        + "        port: 7002\n"
        + "        scheme: HTTPS\n"
        + "      initialDelaySeconds: 1\n"
        + "      periodSeconds: 3\n"
        + "      timeoutSeconds: 2\n"
        + "    resources:\n"
        + "      limits: {}\n"
        + "      requests: {}\n"
        + "    securityContext: {}\n"
        + "    volumeMounts:\n"
        + "    - mountPath: /weblogic-operator/scripts\n"
        + "      name: weblogic-scripts-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/debug\n"
        + "      name: weblogic-domain-debug-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/introspector\n"
        + "      name: weblogic-domain-introspect-cm-volume\n"
        + "  hostname: uid1-admin-server\n"
        + "  imagePullSecrets: []\n"
        + "  initContainers: []\n"
        + "  nodeSelector: {}\n"
        + "  securityContext: {}\n"
        + "  volumes:\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: weblogic-scripts-cm\n"
        + "    name: weblogic-scripts-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-debug-cm\n"
        + "      optional: true\n"
        + "    name: weblogic-domain-debug-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-introspect-cm\n"
        + "    name: weblogic-domain-introspect-cm-volume\n";

  static final String MANAGED_MII_POD_3_1 =
        "metadata:\n"
        + "  annotations:\n"
        + "    prometheus.io/path: /wls-exporter/metrics\n"
        + "    prometheus.io/port: '8001'\n"
        + "    prometheus.io/scrape: 'true'\n"
        + "    weblogic.sha256: bdebf4e8152fea393e06f037bbb4ed243a938f2f9e1aeeffe20768724a0b32cc\n"
        + "  labels:\n"
        + "    weblogic.domainName: domain1\n"
        + "    weblogic.serverName: ess_server1\n"
        + "    weblogic.modelInImageModelSecretsHash: md5.originalSecret.md5\n"
        + "    weblogic.domainRestartVersion: null\n"
        + "    weblogic.domainUID: uid1\n"
        + "    weblogic.createdByOperator: 'true'\n"
        + "    weblogic.modelInImageDomainZipHash: md5.originalSecret.md5\n"
        + "    weblogic.clusterRestartVersion: null\n"
        + "    weblogic.serverRestartVersion: null\n"
        + "  name: uid1-ess-server1\n"
        + "  namespace: namespace\n"
        + "spec:\n"
        + "  containers:\n"
        + "  - command:\n"
        + "    - /weblogic-operator/scripts/startServer.sh\n"
        + "    env:\n"
        + "    - name: DOMAIN_NAME\n"
        + "      value: domain1\n"
        + "    - name: DOMAIN_HOME\n"
        + "      value: /u01/oracle/user_projects/domains\n"
        + "    - name: ADMIN_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: ADMIN_PORT\n"
        + "      value: '7001'\n"
        + "    - name: SERVER_NAME\n"
        + "      value: ess_server1\n"
        + "    - name: DOMAIN_UID\n"
        + "      value: uid1\n"
        + "    - name: NODEMGR_HOME\n"
        + "      value: /u01/nodemanager\n"
        + "    - name: LOG_HOME\n"
        + "    - name: SERVER_OUT_IN_POD_LOG\n"
        + "      value: 'true'\n"
        + "    - name: SERVICE_NAME\n"
        + "      value: uid1-ess-server1\n"
        + "    - name: AS_SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: USER_MEM_ARGS\n"
        + "      value: -Djava.security.egd=file:/dev/./urandom\n"
        + "    - name: ADMIN_USERNAME\n"
        + "    - name: ADMIN_PASSWORD\n"
        + "    image: image:latest\n"
        + "    imagePullPolicy: Always\n"
        + "    lifecycle:\n"
        + "      preStop:\n"
        + "        exec:\n"
        + "          command:\n"
        + "          - /weblogic-operator/scripts/stopServer.sh\n"
        + "    livenessProbe:\n"
        + "      exec:\n"
        + "        command:\n"
        + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
        + "      failureThreshold: 1\n"
        + "      initialDelaySeconds: 4\n"
        + "      periodSeconds: 6\n"
        + "      timeoutSeconds: 5\n"
        + "    name: weblogic-server\n"
        + "    ports:\n"
        + "    - containerPort: 8001\n"
        + "      name: default\n"
        + "      protocol: TCP\n"
        + "    readinessProbe:\n"
        + "      failureThreshold: 1\n"
        + "      httpGet:\n"
        + "        path: /weblogic/ready\n"
        + "        port: 8001\n"
        + "      initialDelaySeconds: 1\n"
        + "      periodSeconds: 3\n"
        + "      timeoutSeconds: 2\n"
        + "    resources:\n"
        + "      limits: {}\n"
        + "      requests: {}\n"
        + "    securityContext: {}\n"
        + "    volumeMounts:\n"
        + "    - mountPath: /weblogic-operator/scripts\n"
        + "      name: weblogic-scripts-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/debug\n"
        + "      name: weblogic-domain-debug-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/introspector\n"
        + "      name: weblogic-domain-introspect-cm-volume\n"
        + "  imagePullSecrets: []\n"
        + "  initContainers: []\n"
        + "  nodeSelector: {}\n"
        + "  securityContext: {}\n"
        + "  volumes:\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: weblogic-scripts-cm\n"
        + "    name: weblogic-scripts-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-debug-cm\n"
        + "      optional: true\n"
        + "    name: weblogic-domain-debug-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-introspect-cm\n"
        + "    name: weblogic-domain-introspect-cm-volume";

  static final String ADMIN_MII_POD_3_1 =
        "metadata:\n"
        + "  annotations:\n"
        + "    prometheus.io/path: /wls-exporter/metrics\n"
        + "    prometheus.io/port: '7001'\n"
        + "    prometheus.io/scrape: 'true'\n"
        + "    weblogic.sha256: 98ac04bc5ddbc792ee37912ea5efe8097016ed10ce93b13f8e57013547429e6c\n"
        + "  labels:\n"
        + "    weblogic.domainName: domain1\n"
        + "    weblogic.serverName: ADMIN_SERVER\n"
        + "    weblogic.modelInImageModelSecretsHash: md5.originalSecret.md5\n"
        + "    weblogic.domainRestartVersion: null\n"
        + "    weblogic.domainUID: uid1\n"
        + "    weblogic.createdByOperator: 'true'\n"
        + "    weblogic.modelInImageDomainZipHash: md5.originalSecret.md5\n"
        + "    weblogic.clusterRestartVersion: null\n"
        + "    weblogic.serverRestartVersion: null\n"
        + "  name: uid1-admin-server\n"
        + "  namespace: namespace\n"
        + "spec:\n"
        + "  containers:\n"
        + "  - command:\n"
        + "    - /weblogic-operator/scripts/startServer.sh\n"
        + "    env:\n"
        + "    - name: DOMAIN_NAME\n"
        + "      value: domain1\n"
        + "    - name: DOMAIN_HOME\n"
        + "      value: /u01/oracle/user_projects/domains\n"
        + "    - name: ADMIN_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: ADMIN_PORT\n"
        + "      value: '7001'\n"
        + "    - name: SERVER_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: DOMAIN_UID\n"
        + "      value: uid1\n"
        + "    - name: NODEMGR_HOME\n"
        + "      value: /u01/nodemanager\n"
        + "    - name: LOG_HOME\n"
        + "    - name: SERVER_OUT_IN_POD_LOG\n"
        + "      value: 'true'\n"
        + "    - name: SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: AS_SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: USER_MEM_ARGS\n"
        + "      value: -Djava.security.egd=file:/dev/./urandom\n"
        + "    - name: ADMIN_USERNAME\n"
        + "    - name: ADMIN_PASSWORD\n"
        + "    image: image:latest\n"
        + "    imagePullPolicy: Always\n"
        + "    lifecycle:\n"
        + "      preStop:\n"
        + "        exec:\n"
        + "          command:\n"
        + "          - /weblogic-operator/scripts/stopServer.sh\n"
        + "    livenessProbe:\n"
        + "      exec:\n"
        + "        command:\n"
        + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
        + "      failureThreshold: 1\n"
        + "      initialDelaySeconds: 4\n"
        + "      periodSeconds: 6\n"
        + "      timeoutSeconds: 5\n"
        + "    name: weblogic-server\n"
        + "    ports:\n"
        + "    - containerPort: 7001\n"
        + "      name: default\n"
        + "      protocol: TCP\n"
        + "    readinessProbe:\n"
        + "      failureThreshold: 1\n"
        + "      httpGet:\n"
        + "        path: /weblogic/ready\n"
        + "        port: 7001\n"
        + "      initialDelaySeconds: 1\n"
        + "      periodSeconds: 3\n"
        + "      timeoutSeconds: 2\n"
        + "    resources:\n"
        + "      limits: {}\n"
        + "      requests: {}\n"
        + "    securityContext: {}\n"
        + "    volumeMounts:\n"
        + "    - mountPath: /weblogic-operator/scripts\n"
        + "      name: weblogic-scripts-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/debug\n"
        + "      name: weblogic-domain-debug-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/introspector\n"
        + "      name: weblogic-domain-introspect-cm-volume\n"
        + "  hostname: uid1-admin-server\n"
        + "  imagePullSecrets: []\n"
        + "  initContainers: []\n"
        + "  nodeSelector: {}\n"
        + "  securityContext: {}\n"
        + "  volumes:\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: weblogic-scripts-cm\n"
        + "    name: weblogic-scripts-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-debug-cm\n"
        + "      optional: true\n"
        + "    name: weblogic-domain-debug-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-introspect-cm\n"
        + "    name: weblogic-domain-introspect-cm-volume";
}
