// Copyright (c) 2021, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

package oracle.kubernetes.operator.helpers;

public class ReferenceObjects {
  static final String MANAGED_POD_3_1 =
        "metadata:\n"
        + "  annotations:\n"
        + "    prometheus.io/path: /wls-exporter/metrics\n"
        + "    prometheus.io/port: '8001'\n"
        + "    prometheus.io/scrape: 'true'\n"
        + "    weblogic.sha256: bdebf4e8152fea393e06f037bbb4ed243a938f2f9e1aeeffe20768724a0b32cc\n"
        + "  labels:\n"
        + "    weblogic.domainName: domain1\n"
        + "    weblogic.serverName: ess_server1\n"
        + "    weblogic.modelInImageModelSecretsHash: md5.originalSecret.md5\n"
        + "    weblogic.domainRestartVersion: null\n"
        + "    weblogic.domainUID: uid1\n"
        + "    weblogic.createdByOperator: 'true'\n"
        + "    weblogic.modelInImageDomainZipHash: md5.originalSecret.md5\n"
        + "    weblogic.clusterRestartVersion: null\n"
        + "    weblogic.serverRestartVersion: null\n"
        + "  name: uid1-ess-server1\n"
        + "  namespace: namespace\n"
        + "spec:\n"
        + "  containers:\n"
        + "  - command:\n"
        + "    - /weblogic-operator/scripts/startServer.sh\n"
        + "    env:\n"
        + "    - name: DOMAIN_NAME\n"
        + "      value: domain1\n"
        + "    - name: DOMAIN_HOME\n"
        + "      value: /u01/oracle/user_projects/domains\n"
        + "    - name: ADMIN_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: ADMIN_PORT\n"
        + "      value: '7001'\n"
        + "    - name: SERVER_NAME\n"
        + "      value: ess_server1\n"
        + "    - name: DOMAIN_UID\n"
        + "      value: uid1\n"
        + "    - name: NODEMGR_HOME\n"
        + "      value: /u01/nodemanager\n"
        + "    - name: LOG_HOME\n"
        + "    - name: SERVER_OUT_IN_POD_LOG\n"
        + "      value: 'true'\n"
        + "    - name: SERVICE_NAME\n"
        + "      value: uid1-ess-server1\n"
        + "    - name: AS_SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: USER_MEM_ARGS\n"
        + "      value: -Djava.security.egd=file:/dev/./urandom\n"
        + "    - name: ADMIN_USERNAME\n"
        + "    - name: ADMIN_PASSWORD\n"
        + "    image: image:latest\n"
        + "    imagePullPolicy: Always\n"
        + "    lifecycle:\n"
        + "      preStop:\n"
        + "        exec:\n"
        + "          command:\n"
        + "          - /weblogic-operator/scripts/stopServer.sh\n"
        + "    livenessProbe:\n"
        + "      exec:\n"
        + "        command:\n"
        + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
        + "      failureThreshold: 1\n"
        + "      initialDelaySeconds: 4\n"
        + "      periodSeconds: 6\n"
        + "      timeoutSeconds: 5\n"
        + "    name: weblogic-server\n"
        + "    ports:\n"
        + "    - containerPort: 8001\n"
        + "      name: default\n"
        + "      protocol: TCP\n"
        + "    readinessProbe:\n"
        + "      failureThreshold: 1\n"
        + "      httpGet:\n"
        + "        path: /weblogic/ready\n"
        + "        port: 8001\n"
        + "      initialDelaySeconds: 1\n"
        + "      periodSeconds: 3\n"
        + "      timeoutSeconds: 2\n"
        + "    resources:\n"
        + "      limits: {}\n"
        + "      requests: {}\n"
        + "    securityContext: {}\n"
        + "    volumeMounts:\n"
        + "    - mountPath: /weblogic-operator/scripts\n"
        + "      name: weblogic-scripts-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/debug\n"
        + "      name: weblogic-domain-debug-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/introspector\n"
        + "      name: weblogic-domain-introspect-cm-volume\n"
        + "  imagePullSecrets: []\n"
        + "  initContainers: []\n"
        + "  nodeSelector: {}\n"
        + "  securityContext: {}\n"
        + "  volumes:\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: weblogic-scripts-cm\n"
        + "    name: weblogic-scripts-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-debug-cm\n"
        + "      optional: true\n"
        + "    name: weblogic-domain-debug-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-introspect-cm\n"
        + "    name: weblogic-domain-introspect-cm-volume";

  static final String ADMIN_POD_3_1 =
        "metadata:\n"
        + "  annotations:\n"
        + "    prometheus.io/path: /wls-exporter/metrics\n"
        + "    prometheus.io/port: '7001'\n"
        + "    prometheus.io/scrape: 'true'\n"
        + "    weblogic.sha256: 98ac04bc5ddbc792ee37912ea5efe8097016ed10ce93b13f8e57013547429e6c\n"
        + "  labels:\n"
        + "    weblogic.domainName: domain1\n"
        + "    weblogic.serverName: ADMIN_SERVER\n"
        + "    weblogic.modelInImageModelSecretsHash: md5.originalSecret.md5\n"
        + "    weblogic.domainRestartVersion: null\n"
        + "    weblogic.domainUID: uid1\n"
        + "    weblogic.createdByOperator: 'true'\n"
        + "    weblogic.modelInImageDomainZipHash: md5.originalSecret.md5\n"
        + "    weblogic.clusterRestartVersion: null\n"
        + "    weblogic.serverRestartVersion: null\n"
        + "  name: uid1-admin-server\n"
        + "  namespace: namespace\n"
        + "spec:\n"
        + "  containers:\n"
        + "  - command:\n"
        + "    - /weblogic-operator/scripts/startServer.sh\n"
        + "    env:\n"
        + "    - name: DOMAIN_NAME\n"
        + "      value: domain1\n"
        + "    - name: DOMAIN_HOME\n"
        + "      value: /u01/oracle/user_projects/domains\n"
        + "    - name: ADMIN_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: ADMIN_PORT\n"
        + "      value: '7001'\n"
        + "    - name: SERVER_NAME\n"
        + "      value: ADMIN_SERVER\n"
        + "    - name: DOMAIN_UID\n"
        + "      value: uid1\n"
        + "    - name: NODEMGR_HOME\n"
        + "      value: /u01/nodemanager\n"
        + "    - name: LOG_HOME\n"
        + "    - name: SERVER_OUT_IN_POD_LOG\n"
        + "      value: 'true'\n"
        + "    - name: SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: AS_SERVICE_NAME\n"
        + "      value: uid1-admin-server\n"
        + "    - name: USER_MEM_ARGS\n"
        + "      value: -Djava.security.egd=file:/dev/./urandom\n"
        + "    - name: ADMIN_USERNAME\n"
        + "    - name: ADMIN_PASSWORD\n"
        + "    image: image:latest\n"
        + "    imagePullPolicy: Always\n"
        + "    lifecycle:\n"
        + "      preStop:\n"
        + "        exec:\n"
        + "          command:\n"
        + "          - /weblogic-operator/scripts/stopServer.sh\n"
        + "    livenessProbe:\n"
        + "      exec:\n"
        + "        command:\n"
        + "        - /weblogic-operator/scripts/livenessProbe.sh\n"
        + "      failureThreshold: 1\n"
        + "      initialDelaySeconds: 4\n"
        + "      periodSeconds: 6\n"
        + "      timeoutSeconds: 5\n"
        + "    name: weblogic-server\n"
        + "    ports:\n"
        + "    - containerPort: 7001\n"
        + "      name: default\n"
        + "      protocol: TCP\n"
        + "    readinessProbe:\n"
        + "      failureThreshold: 1\n"
        + "      httpGet:\n"
        + "        path: /weblogic/ready\n"
        + "        port: 7001\n"
        + "      initialDelaySeconds: 1\n"
        + "      periodSeconds: 3\n"
        + "      timeoutSeconds: 2\n"
        + "    resources:\n"
        + "      limits: {}\n"
        + "      requests: {}\n"
        + "    securityContext: {}\n"
        + "    volumeMounts:\n"
        + "    - mountPath: /weblogic-operator/scripts\n"
        + "      name: weblogic-scripts-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/debug\n"
        + "      name: weblogic-domain-debug-cm-volume\n"
        + "      readOnly: true\n"
        + "    - mountPath: /weblogic-operator/introspector\n"
        + "      name: weblogic-domain-introspect-cm-volume\n"
        + "  hostname: uid1-admin-server\n"
        + "  imagePullSecrets: []\n"
        + "  initContainers: []\n"
        + "  nodeSelector: {}\n"
        + "  securityContext: {}\n"
        + "  volumes:\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: weblogic-scripts-cm\n"
        + "    name: weblogic-scripts-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-debug-cm\n"
        + "      optional: true\n"
        + "    name: weblogic-domain-debug-cm-volume\n"
        + "  - configMap:\n"
        + "      defaultMode: 365\n"
        + "      name: uid1-weblogic-domain-introspect-cm\n"
        + "    name: weblogic-domain-introspect-cm-volume";
}
