# Copyright 2018, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.domainUID }}-weblogic-domain-job-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    weblogic.resourceVersion: domain-v1
    weblogic.domainUID: {{ .Values.domainUID }}
    weblogic.domainName: {{ .Values.domainName }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  storageClassName: {{ .Values.domainUID }}-weblogic-domain-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.weblogicDomainStorageSize }}
