{{- if eq .Values.loadBalancer "APACHE" }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.domainUID }}-apache-webtier
  labels:
    weblogic.resourceVersion: apache-load-balancer-v1
    weblogic.domainUID: {{ .Values.domainUID }}
    weblogic.domainName: {{ .Values.domainName }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.domainUID }}-apache-webtier
  labels:
    weblogic.resourceVersion: apache-load-balancer-v1
    weblogic.domainUID: {{ .Values.domainUID }}
    weblogic.domainName: {{ .Values.domainName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.domainUID }}-apache-webtier
subjects:
- kind: ServiceAccount
  name: {{ .Values.domainUID }}-apache-webtier
  namespace: {{ .Release.Namespace }}
{{- end }}
