# Copyright (c) 2018, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: %STORAGE_CLASS_NAME%
provisioner: file.csi.azure.com
parameters:
  protocol: nfs
  resourceGroup: %STORAGE_ACCOUNT_RESOURCE_GROUP_NAME%
  storageAccount: %STORAGE_ACCOUNT_NAME%
  shareName: %AZURE_FILE_SHARE_NAME%
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true